### PR TITLE
Added World.GetDistanceTo

### PR DESCRIPTION
**Pull request by ricci07**
Added Ped.GetDistanceTo
Entity.GetDistanceTo
Vehicle.GetDistanceTo
Game.PlayMusic
Game.StopMusic

### CODE REVIEW

**Comment by crosire** [comment]
What was wrong?

**Comment by ricci07** [comment]
Well I did about 5 new methods but GitHub said there was merge conflicts or something. (I am 13 commits behind you) Still a fuzzy with git. Do I need get the latest master from you before adding new stuff in.

**Comment by crosire** [comment]
You don't need to care about that, such conflicts can be resolved during the merging.

**Comment by ricci07** [comment]
Ah I had second thoughts, Ok I 'think' that is everything that I need to know about git. Gonna do a rebase this time and then repush the branch so everything is clean somewhat.

**Pull request closed without merging**
