### PR TITLE
Added support for Ray Casting, Ped Bones, plus other fixes

### PR DESCRIPTION
**Pull request by zorg93**
Updated Notify so it now returns notification handle
Added Method to delete a notification from its handle
Uncompiled CS files can use unsafe code

### CODE REVIEW

**Comment by Nacorpio** [comment]
Very good job.

**Comment by JohnnyCrazy** [comment]
Uhm, out of interest, when does `GET_SCREEN_RESOLUTION` not return 1280:720?

**Comment by Frede1012** [comment]
@JohnnyCrazy Just ran the code, can confirm, still returns 1280x720.

**Comment by IncoCode** [comment]
Maybe, we can use size structure instead of two properties?

**Comment by IncoCode** [comment]
@JohnnyCrazy , never =\

**Comment by JohnnyCrazy** [comment]
I don't see any reason changing it then? It will just use more calls (2, not even 1) and doesn't feature any improvements

**Comment by Frede1012** [comment]
@JohnnyCrazy Me neither, however the notification code seems cool (havent tested it though).

**Comment by zorg93** [comment]
//----- (000000013FCE6124) ----------------------------------------------------
__int64 __fastcall sub_13FCE6124(__int64 a1)
{
  __int64 v1; // rax@1
  __int64 v2; // rcx@1
  __int64 result; // rax@1

  v1 = *(_QWORD *)(a1 + 16);
  v2 = *(_QWORD *)(v1 + 8);
  result = *(_QWORD *)v1;
  *(_DWORD *)result = 1280;
  *(_DWORD *)v2 = 720;
  return result;
}

Hmm, never mind, just checked the gtav exe, that bit of code can be removed

**Comment by JohnnyCrazy** [comment]
Just a quick note:
Maybe we can use a small wrapper for the map notifications, something like this?
````c#
Notification not = UI.Notify("test", 10000); //Automatically shows it?
//Do some other stuff
not.Hide() //or Remove

**Comment by zorg93** [comment]
That could work, but making a wrapper when there is only 2 methods you can really use (show and hide) seems like a waste of time

**Comment by Frede1012** [comment]
Seems easier to handle a bunch of notification objects then integer ids?

**Comment by frodzet** [comment]
"Uncompiled CS files can use unsafe code"

So we can now work with pointers etc? :-D

**Comment by zorg93** [comment]
It lets you work directly with pointers using cs files, you could use pointers with c# already, but you need to compile them as a dll in visual studio beforehand. this means you can release a cs script(people wont be scared about viruses) and still make use of pointers

**Comment by zorg93** [comment]
Changed Notification so they are now a Class
//usage
UI.Notification Notify = new UI.Notification("Message", bBlinking); //bBlinking is a bool, true to make the notification blink
//To Delete
Notify.Delete();

**Comment by JohnnyCrazy** [comment]
Seems cool to me :+1: @crosire

**Comment by crosire** [comment]
But it breaks existing scripts using UI.Notify ... Should at least keep it and mark it obsolete.

**Comment by nevadascout** [comment]
Agreed. UI.Notify() should be kept - it's a useful debug function.

**Comment by JohnnyCrazy** [comment]
Or change it to `Notification not = UI.Notify("test");`, so it won't break.

Would also be better since we are just using methods (like e.g `World.CreateVehicle`) to create actual stuff ingame, not constructors.

**Comment by zorg93** [comment]
Put the old method back in for older scripts

**Comment by zorg93** [comment]
@JohnnyCrazy @crosire Are there any other issues with this that need fixing first

**Comment by Frede1012** [comment]
Seems weird to be implementing it like that, that a constructor creates a notification by itself.
Using UI.Notify seems like the best choice.. Older scripts won't break just because it now returns an object will they??

**Comment by zorg93** [comment]
@Frede1012 The issue is not with cs or vb files, but dll files will break, anyway changed it again to how the messagebox class in windows works. also added a few other little fixes

**Comment by zorg93** [comment]
@JohnnyCrazy I have made a class for using Ray casting, there are still a few unknowns in there, but its good enough to start to work with.

**Comment by JohnnyCrazy** [comment]
Don't wanna decide alone on this, will leave this to @crosire :D

**Comment by crosire** [comment]
I like most of the changes, but I'm still not happy with the notification class. "UI::Notify" was much simpler to use and the amount of classes is constantly growing and growing ...
Could we split this in two pull requests and further discuss the notification stuff?

**Comment by nevadascout** [comment]
Nothing wrong with having lots of classes! :)

**Comment by crosire** [comment]
@nevadascout I'm a big supporter of the KISS principle =P

**Comment by nevadascout** [comment]
True, but having lots of classes is simpler than one class that does everything in my opinion :P

There's also the Single Responsibility Principal to consider

**Comment by zorg93** [comment]
@crosire right I've removed the notification stuff, arent experienced enough with GIT to make 2 different requests

**Pull request merged**
