### PR TITLE
Add Vehicle.Type and add getter methods to Vehicle for VehicleType

### PR DESCRIPTION
**Pull request by kagikn**
I believe this is worth adding because even the exe checks this value instead of the equivalent value in `CVehicleModelInfo` so many times. Rockstar use the same strategy in SA. For example, natives for vehicle tires such as `IS_VEHICLE_TYRE_BURST` work only if this value is `0xC` or less, and `SET_VEHICLE_DROPS_MONEY_WHEN_BLOWN_UP` actually changes the field value only if this value is `0xA` or less.
Maybe there are more obvious names than `VehicleType`, though.

### CODE REVIEW

**Comment by kagikn** [comment]
This PR also includes the changes to find the  vehicle type offset in `CVehicleModelInfo` rather than the fixed value. Had to fix the problem to make the 2 added methods in `Vehicle` work, and the change also fixes model property such as `Model.IsMotorcycle`.

**Comment by crosire** [comment]
From a correctness perspective I see the benefit of this. But it is rather similar to `VehicleClass`, apart from more distinction related to water vehicles, so I'm not fully convinced it to be useful to script development?

**Comment by kagikn** [comment]
Looks like I need to explain differently. `VehicleClass` and `VehicleType` values are defined with `type` and `vehicleClass` respectively in `vehicles.meta`.  If I undersand how the exe works correctly, `vehicleClass` values don't affect how vehicles behave except automobiles can whillie if `vehicleClass` is set to `VC_MUSCLE` (`VehicleClass.Muscle`). However, `type` values in `vehicles.meta` do affect how vehicles behave.

Another benefit is about performance. Boats, trains, and Submarine don't have wheels, but we have to check vehicle types like this with the content main branch currently has;
```C#
//// in VehicleWheel. I'm planning to add this property
    public int Health // wheel health
    {
        get
        {
            var model = Owner.Model;
            if (model.IsBoat || model.IsTrain || model.IsSubmarine)
            {
                return 0.0f;
            }

           return SHVDN.NativeMemory.ReadFloat(address + SHVDN.NativeMemory.VehicleWheelHealthOffset);
        }
    }
```
With `VehicleType`, we can do like this (performs faster)
```C#
    public int Health // wheel health
    {
        get
        {
            var vehicleType = Owner.Type; // no further external memory access for vehicle type checl
            if (vehicleType == VehicleType.Boat || vehicleType == VehicleType.Train || vehicleType == VehicleType.Submarine)
            {
                return 0.0f;
            }

           return SHVDN.NativeMemory.ReadFloat(address + SHVDN.NativeMemory.VehicleWheelHealthOffset);
        }
    }
```
If you aren't still fully convinced with these explanation, I'll explain the benefits with other instances.

**Comment by kagikn** [comment]
Btw, the trikes added with GTA updates so far (`VehicleHash.Chimera`, `VehicleHash.RRocket`, `VehicleHash.Stryder`) are defined as quad bikes (`CQuadBike`, which is a subclass of `CAutomobile`), not motorcycles `(`CBike`, which is a direct subclass of `CVehicle`).

**Comment by kagikn** [comment]
If you check the vehicle type via `Model`, get the vehicle address, get the model info address via the vehicle address and get the model name hash first. And then, search the model info array for the model info with specified hash, and compare the vehicle type value under the hood.
If you compare the vehicle type using the vehicle type value in `CVehicle`, you get the vehicle address and grab the vehicle type value and compare, that’s it. Definitely faster than the comparison with the vehicle type value in `CVehicleModelInfo`.

**Review by crosire — APPROVED** [review]
Fair enough!

**Pull request merged**
