### PR TITLE
Add Menu GUI abstraction

### PR DESCRIPTION
**Pull request by StijnBrouwer**

### CODE REVIEW

**Comment by StijnBrouwer** [comment]
I'll fix the float to int conversion warning now

**Comment by StijnBrouwer** [comment]
I think the API is now done. I will port @Nacorpio's stuff over to `MenuItem`s though.

**Comment by crosire** [comment]
May I suggest to merge MenuScript and Script into Script? We don't really need them separated.

**Comment by StijnBrouwer** [comment]
Okay

**Comment by StijnBrouwer** [comment]
Oh, I see you added a license too, I'll add the notice above my files too

**Comment by crosire** [comment]
It's only in the core files, the scripting API does not have that header.

**Comment by StijnBrouwer** [comment]
Oh okay

**Comment by StijnBrouwer** [comment]
I think it's ready to go now, I'll work on porting @Nacorpio's stuff in my own fork.

**Comment by StijnBrouwer** [comment]
Oh, what, I think visual studio didn't save correctly

**Comment by StijnBrouwer** [comment]
Because you can only use case on a static expression

I made it so that you can redefine what keys trigger the menu, with `Script.ActivateKey` and all those fields.

**Comment by crosire** [comment]
Ah. It looked like those were constants at first.

**Comment by StijnBrouwer** [comment]
So, is it ready to be merged?

**Comment by crosire** [comment]
Doing that right now.

**Comment by StijnBrouwer** [comment]
Okay

**Comment by JohnnyCrazy** [comment]
Wow, cool changes! :+1: 
Would you mind adding some example code to the top-post? This would definitely help a lot of people!

**Comment by StijnBrouwer** [comment]
I already have an example script: https://github.com/crosire/scripthookvdotnet/blob/master/example/MenuScripts.cs

But it's still all work in progress. I'm adding new `MenuItem`s in my own fork. And there's still some kinks to iron out. One of them is that `Menu`s get instantiated with a position specified by the `Viewport` and that it's hard to change that position once the menu has been instantiated. But I'm almost done with a fix for that.

**Comment by StijnBrouwer** [comment]
I just fixed that: https://github.com/StijnBrouwer/scripthookvdotnet/commit/0b5c64d85de6fe187081b65fc0e513742b9263f5

**Comment by StijnBrouwer** [comment]
I'll continue discussion in https://github.com/crosire/scripthookvdotnet/issues/8

**Pull request merged**
