### PR TITLE
Tick ScriptDomain in a seperate thread

### PR DESCRIPTION
**Pull request by Sardelka9515**
Eliminate the need of the `ForceCLRInit` hack, which can sometimes cause crash during first session load as mentioned in [#1169 (comment)](https://github.com/crosire/scripthookvdotnet/issues/1169#issuecomment-1448368054). Performance may be slightly impacted.

### CODE REVIEW

**Comment by crosire** [comment]
Brings back dispatching between threads, but at least keeps that down to once per tick. But looks like `CLRThreadProc` can never exit (which could prevent the process from exiting cleanly)? Also why is the change to ScriptDomain.cs needed?

**Comment by crosire** [comment]
The only way I could come up with to do this with clean exiting is this:
```c++
static DWORD CLRThreadProc(LPVOID lparam)
{
	// Increment reference count of the ScriptHookVDotNet module
	HMODULE module = nullptr;
	GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, reinterpret_cast<LPCTSTR>(&CLRThreadProc), &module);

	LPVOID tlsContextOrg = GetTlsContext();

	WaitForSingleObject(hCLRContinueEvent, INFINITE);

	while (true)
	{
		SetTlsContext(GameTls);
		ScriptHookVDotNet_ManagedInit();
		SetTlsContext(tlsContextOrg);

		sGameReloaded = false;

		while (!sGameReloaded)
		{
			SetTlsContext(GameTls);
			ScriptHookVDotNet_ManagedTick();
			SetTlsContext(tlsContextOrg);

			SetEvent(hCLRWaitEvent);
			if (WaitForSingleObject(hCLRContinueEvent, 5000) != WAIT_OBJECT_0)
			{
				// Did not receive a tick from ScriptHookV for several seconds, assume ScriptHookVDotNet was freed by it and finish cleaning up and actually unloading
				ScriptHookVDotNet_ManagedUninit(); // This just unloads the scrippt domain
				FreeLibraryAndExitThread(module, 0);
				return 0;
			}
		}
	}

	return 0;
}
```
That should cause everything SHVDN created to exit cleanly, which might even fix #547. Untested though, there is danger that the timeout is triggered during loading screens or similar too ...

**Comment by Sardelka9515** [comment]
Does SHV ticks the script when the game is paused? This could also cause some problem if other scripts takes longer than 5 seconds to execute?

One thing i came up with is to increment the dll refcount in dllmain using `LoadLibrary` or `GetModuleHandle`, which prevents the dll from being unmapped when SHV reloads, then check the current ref count in clr thread, which can be retrieved with from a linked list in PEB, and exit the thread/free library if the ref count reached 1.

**Comment by kagikn** [comment]
> Does SHV ticks the script when the game is paused? This could also cause some problem if other scripts takes longer than 5 seconds to execute?

Probably not. I heard RPH has `ShouldTickInPauseMenu` so the plugin can tick while the pause menu is shown, but I couldn't make SHV scripts tick in that condition. Here's the test code I used:
```cpp
int nextTick = 0;

void ScriptMain()
{	
	while (true) {
	int nowTimer = MISC::GET_GAME_TIMER();
	if (nowTimer > nextTick) {
		nextTick = nowTimer + 5000;

		if (HUD::GET_PAUSE_MENU_STATE()) {
			std::ofstream writing_file;
			writing_file.open("PauseMenuTest.txt", std::ios::out); // the file should be written in the directory where GTA5.exe is located if the code went to this path
			writing_file << "Yay! I can do something while the pause menu is shown!" << std::endl;
		}
	}
	scriptWait(0);
}
}
```

**Comment by Sardelka9515** [comment]
The ref count workaround is a bit more cumbersome than i initially thought. Since it's undocumented, Microsoft will (and had) changed the internal `LDR_DATA_TABLE_ENTRY` layout. For example, the reference count was stored as a USHORT at ldr+0x6c in Windows 7 and earlier, but moved to `LDR_DDAG_NODE` in Windows 8, then moved to ldr+0x114 in Windows 10 or later.

**Comment by Sardelka9515** [comment]
Managed to get most thing working, but SHV does not unregistering script from another thread, so it'll result in a `Fatal: attempt to unregister script unk 0x.....` error when trying to reload. If the script is not unregistered the process will crash badly

**Comment by Sardelka9515** [comment]
Another thought, maybe hooking `FreeLibrary` will work as well

**Comment by Sardelka9515** [comment]
I don't think proper termination would be possible with using pure unmanaged asi/introducing another dll.
During the test I found that the CLR will increment the asi's load count during the first call to **actual** managed function (not necessarily the one compiled as MSIL), which I assume is the reason why DllMain is not called during SHV reload.

Closing this as I think 6b6191f4c2b8f98f8fa362a72f0285eb216089b2 will be better off in another PR

**Pull request closed without merging**
