### PR TITLE
Menus now how vertical scrolling

### PR DESCRIPTION
**Pull request by zorg93**
you can have as many menu items in a menu as you want and they will appear/disappear as you scroll up/down the menu

### CODE REVIEW

**Comment by zorg93** [comment]
Heres an idea what the scrolling looks like
http://puu.sh/j0DgL/7ee724acf5.png - top of menu
http://puu.sh/j0Dm3/5a7ca13325.png - middle of menu
http://puu.sh/j0Dp9/cf67991f4e.png - bottom of menu

**Comment by crosire** [comment]
Nice job!

**Comment by frodzet** [comment]
Perfect!

**Comment by IncoCode** [comment]
How about to implement scrollable menu as separate class which will inherit from Menu class?
I think we should have a "clean" menu class based on which we can create our custom menus: like this ScrollableMenu, [ListMenu](https://github.com/crosire/scripthookvdotnet/issues/221#issuecomment-115214737) and etc.

**Comment by zorg93** [comment]
The menu scrolling only comes into play if there are enough items in the menu, without enough items, it just functions identically to how the menu class used to be. Also the whole menu class is going to be changed again for the 2.0 release. Also that ListMenu could still inherit from the scrollable menu and function the same, just make sure the maxitemsdrawn property is the same as what you have in ListMenu

**Comment by IncoCode** [comment]
@zorg93 oh, okay, thanks for answer. You didn't mention this in first comment and today i'm too lazy to watch the sources :stuck_out_tongue:

**Pull request merged**
