### PR TITLE
TaskSequence

### PR DESCRIPTION
**Pull request by IncoCode**
It seems like it's working :smile:
Example:
```c#
TaskSequence s = new TaskSequence();
s.AddTask.EnterVehicle( veh, VehicleSeat.Driver );
s.AddTask.DriveTo( veh, pos, 2, 30 );
s.AddTask.LeaveVehicle();
s.CloseSequence();

ped.Task.PerformSequence( s );
```

### CODE REVIEW

**Comment by Nacorpio** [comment]
That is a great idea.
Good job.

**Comment by crosire** [comment]
Here's my usual suggestion again =): Make TaskSequence a value class and add "Tasks::PerformSequence", so one can do the following:

```c#
TaskSequence s = new TaskSequence();
s.AddTask.EnterVehicle(_veh, VehicleSeat.Driver);
s.AddTask.DriveTo(_veh, _pos, 2, 30);
s.AddTask.LeaveVehicle();

ped.Task.PerformSequence(s);
```

**Comment by IncoCode** [comment]
:+1:  Okay.

**Comment by IncoCode** [comment]
Updated.
P.S. TaskSequence can't be a value class. Because i need a default constructor. It's using for creating new sequence (OPEN_SEQUENCE_TASK) and creating "null ped".

**Pull request merged**
