### PR TITLE
Menu events

### PR DESCRIPTION
**Pull request by IncoCode**
- Renamed MenuItem to IMenuItem;
- Added Yes and No events from MessageBox;
- Removed actions from constructors;
- Added Activated event for MenuButton;
- Added Activated and Changed events for MenuEnumScroller;
- Added Activated and Changed events for MenuNumericScroller;
- Added Activated and Changed item for MenuToggle;
- Removed ListMenu;
- Updated SimpleTrainer example.

~~Let's break all mods.~~

Example:
```c#
var items = new List<IMenuItem>();
foreach ( VehicleHash veh in Enum.GetValues( typeof( VehicleHash ) ) )
{
	var button = new MenuButton( veh.ToString() );
	button.Activated += ( o, args ) =>
	{
		World.CreateVehicle( veh, player.Position.Around( 3f ) );
		UI.ShowSubtitle( "Vehicle spawned!", 2000 );
	};
	items.Add( button );
}
var enumScroller = new MenuEnumScroller( "Enum", "", new[] { "one", "two", "three" } );
enumScroller.Activated +=
	( o, args ) => UI.ShowSubtitle( "Enum activated: " + enumScroller.Value, 2000 );
enumScroller.Changed += ( o, args ) => UI.ShowSubtitle( "Enum changed: " + enumScroller.Value, 2000 );
items.Insert( 0, enumScroller );

var menu = new Menu( "Test", items.ToArray() );
this.View.AddMenu( menu );
```

### CODE REVIEW

**Comment by Frede1012** [comment]
Looks good! :-)

**Comment by Frede1012** [comment]
@IncoCode Did you see my edit?

**Comment by IncoCode** [comment]
@Frede1012 i'm waiting for comments or suggestions by @JohnnyCrazy or @crosire . If they accept this implementation - i will add separate events for MenuItems (if these events are needed).

**Comment by JohnnyCrazy** [comment]
Some things I noted while skimming over it:

* Do we need `ActivateItem`? I see no reason since the actual menu should not care if you activate an item or not, and besides that every MenuItem will have it's own event so or so.
* I would go with other names. `ChangeItem` looks like a funtion or property. I would suggest using `SelectedIndexChanged` (taken out of the WinForms ListBox class)
* MessageBox-changes seem like a good Idea. But maybe we should implement some blocking-call. So it will return a `DialogResult` instead of events. I'm not sure about this one tho

But these are just my opinions, wait for @crosire since I don't want to decide alone on this :)

**Comment by crosire** [comment]
I agree with @JohnnyCrazy's points.

**Comment by IncoCode** [comment]
Well, ```ActivateItem``` could be useful: if we have many MenuItems and need to call the same method, but the argument will depend on the selected item, or for ListMenu:
```c#
var menu = new ListMenu( "Vehicles" );
foreach ( string vehName in Enum.GetNames( typeof( VehicleHash ) ) )
{
	menu.Add( vehName );
}
menu.ActivateItem += ( o, args ) =>
{
	var veh = (VehicleHash)Enum.Parse( typeof( VehicleHash ), args.MenuItem.Item1 );
	World.CreateVehicle( veh, player.Position.Around( 3f ) );
};
this.View.AddMenu( menu );
```

About ```MessageBox```, I need to keep or delete the current implementation?

**Comment by Frede1012** [comment]
I agree that ActivateItem is useful in some cases, but i also think that menu items need their own seperate events :-)

**Comment by JohnnyCrazy** [comment]
Well, but it is kinda "bad practice". We should keep the abstraction levels.

Changing your example:
````c#
var menu = new Menu("Vehicles");
foreach (VehicleHash veh in Enum.GetValues(typeof(VehicleHash)))
{
    MenuButton button = new MenuButton(Enum.GetName(typeof(VehicleHash), veh));
    button.Clicked += (sender, args) => World.CreateVehicle(veh, player.Position.Around(3f));
    menu.Add(button);
}
this.View.AddMenu( menu );
````

BTW:
What is the sense behind `ListMenu`? Where is the difference between a normal Menu with buttons? When I think of a ListMenu (like the ListBox from WinForms), you select one or more items, but you never actually execute one.

**Comment by Frede1012** [comment]
@JohnnyCrazy Ah, i see. That makes sense.

I think the original purpose of ListMenu, was to have a menu that is easier to edit. I am not sure its relevant anymore, since changes.

**Comment by Frede1012** [comment]
Maybe ListMenu should be removed all together?

**Comment by JohnnyCrazy** [comment]
@Frede1012 I agree, it's kind of redundant since you can achieve the same with a normal menu without much effort.

**Comment by IncoCode** [comment]
Update:
- Renamed MenuItem to IMenuItem;
- Added Yes and No events from MessageBox;
- Removed actions from constructors;
- Added Activated event for MenuButton;
- Added Activated and Changed events for MenuEnumScroller;
- Added Activated and Changed events for MenuNumericScroller;
- Added Activated and Changed item for MenuToggle.

**Comment by Frede1012** [comment]
Cool!

**Comment by crosire** [comment]
@IncoCode Mind removing ListMenu altogether too before merging?

**Comment by IncoCode** [comment]
@crosire okay, also I will update SimpleTrainer example.

**Comment by IncoCode** [comment]
Done. Also updated SimpleTrainer example.

**Pull request merged**
