### PR TITLE
GetUserInput fix

### PR DESCRIPTION
**Pull request by EdgeKiller**
Don't know why, but it's need this.

### CODE REVIEW

**Comment by zorg93** [comment]
the reason is the max length also includes the string terminator character('\0'), how its currently set up means if the max length set is 8, you can write 7 chars then the string terminator will be the 8th

**Comment by EdgeKiller** [comment]
Ok thank's for the explication ! But it's better if we dont always need to add one, isn't ?

**Comment by crosire** [comment]
In that case it would be better to change https://github.com/EdgeKiller/scripthookvdotnet/blob/dev/source/Game.cpp#L180 to the following then instead:
```c#
Native::Function::Call(Native::Hash::DISPLAY_ONSCREEN_KEYBOARD, true, windowTitle.ToString(), "", defaultText, "", "", "", maxLength + 1);
```

**Comment by zorg93** [comment]
on the subject of GetUserInput, it would be wise to check if update_onscreen_keyboard = 1(user finished editing) before returning get_onscreen_keyboard_result, if it = 2 then that means the cancelled the input

**Comment by crosire** [comment]
Was fixed in #295.

**Pull request closed without merging**
