### PR TITLE
Add enum comparer to improve performance

### PR DESCRIPTION
**Pull request by kagikn**
The enum constraint is available in C# 7.3 or greater. so time to use this.

### CODE REVIEW

**Comment by crosire** [comment]
Today I learned that dictionaries with enum keys are handled suboptimally in .NET ...

I would consider moving that class into a more generic Helper.cs though, which can be used in case more of these kinds of things are added in the future.

**Comment by kagikn** [comment]
Wait, I found some article that says Dictionaries with enum keys are as fast as primitive types (e.g. int, long) in .NET Framework 4.6 or later.
I guess we don't have to make the enum comparer class for performance. I'll post a simple test code.

**Comment by kagikn** [comment]
Tested with this (I use BenchmarkDotNet because test with `System.Diagnostics.Stopwatch` showed the dictionary with enum keys performed too fast and I thought the result was obviously wrong)
```C#
namespace ConsoleApp
{
    public class DictionaryTest
    {
        private const int repeatNum = 10000000;

        private enum TestEnum
        {
            ID1,
            ID2,
            ID3,
            ID4,
            ID5,
            ID6,
            ID7,
            ID8,
            ID9,
            ID10,
        }

        private enum TestEnum2
        {
            ID11,
            ID12,
            ID13,
            ID14,
            ID15,
            ID16,
            ID17,
            ID18,
            ID19,
            ID20,
        }

        [Benchmark]
        public void RetrieveEnumValueEnumKey()
        {
            var enumDic = new Dictionary<TestEnum, TestEnum2>()
            {
                {TestEnum.ID1, TestEnum2.ID11},
                {TestEnum.ID2, TestEnum2.ID12},
                {TestEnum.ID3, TestEnum2.ID13},
                {TestEnum.ID4, TestEnum2.ID14},
                {TestEnum.ID5, TestEnum2.ID15},
                {TestEnum.ID6, TestEnum2.ID16},
                {TestEnum.ID7, TestEnum2.ID17},
                {TestEnum.ID8, TestEnum2.ID18},
                {TestEnum.ID9, TestEnum2.ID19},
                {TestEnum.ID10, TestEnum2.ID20},
            };

            var tmp = TestEnum2.ID11;

            for (int i = 0; i < repeatNum; i++)
            {
                tmp = enumDic[TestEnum.ID1];
                tmp = enumDic[TestEnum.ID2];
                tmp = enumDic[TestEnum.ID3];
                tmp = enumDic[TestEnum.ID4];
                tmp = enumDic[TestEnum.ID5];
                tmp = enumDic[TestEnum.ID6];
                tmp = enumDic[TestEnum.ID7];
                tmp = enumDic[TestEnum.ID8];
                tmp = enumDic[TestEnum.ID9];
                tmp = enumDic[TestEnum.ID10];
            }
        }


        [Benchmark]
        public void RetrieveEnumValueIntKey()
        {
            var intDic = new Dictionary<int, TestEnum2>()
            {
                {1, TestEnum2.ID11},
                {2, TestEnum2.ID12},
                {3, TestEnum2.ID13},
                {4, TestEnum2.ID14},
                {5, TestEnum2.ID15},
                {6, TestEnum2.ID16},
                {7, TestEnum2.ID17},
                {8, TestEnum2.ID18},
                {9, TestEnum2.ID19},
                {10, TestEnum2.ID20},
            };

            var tmp = TestEnum2.ID11;

            for (int i = 0; i < repeatNum; i++)
            {
                tmp = intDic[1];
                tmp = intDic[2];
                tmp = intDic[3];
                tmp = intDic[4];
                tmp = intDic[5];
                tmp = intDic[6];
                tmp = intDic[7];
                tmp = intDic[8];
                tmp = intDic[9];
                tmp = intDic[10];
            }
        }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<DictionaryTest>();
        }
    }
}
```
**Result**

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17134.523 (1803/April2018Update/Redstone4)
Intel Core i5-4670K CPU 3.40GHz (Haswell), 1 CPU, 4 logical and 4 physical cores
Frequency=3318390 Hz, Resolution=301.3510 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0
  DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3260.0

| Method                   | Mean     | Error   | StdDev    |
|--------------------------|----------|---------|-----------|
| RetrieveEnumValueEnumKey | 976.7 ms | 5.353 ms | 4.745 ms |
| RetrieveEnumValueIntKey  | 973.5 ms | 6.400 ms | 5.674 ms |

I think we don't need to make the enum comparer for performance.

**Comment by crosire** [comment]
Thank you!

**Pull request closed without merging**
