### PR TITLE
Add ReloadAllScripts & AbortAllScripts

### PR DESCRIPTION
**Pull request by kagikn**
I hope the console separate its arguments with spaces as most terminals, not commas, and I hope the console can execute its commands without parenthesis ~~or semicolons~~ as them.

### CODE REVIEW

**Comment by crosire** [comment]
The console is a C# script input window. Commands are C# function calls. You don't need the semicolon, but you sure do need commas and parenthesis. And that's a good thing because it makes the console **very** powerful.

**Comment by kagikn** [comment]
I thought I needed the semicolon, but actually doesn't. It is true that the C# script input window makes the console very powerful, but we could add `Execute` command because most average users will usually call only console commands, I think, and we could add commands like `Kill(ped)` or `Spawn(vehicle)`.
Btw, How about this PR? Is there something wrong with it?

**Comment by Tanjitsu** [comment]
Could pop something into the Wiki showing the basics of the console.

**Comment by kagikn** [comment]
Let me give you an example.
```
Reload testscript.dll
```
I'd like to call ordinary console commands like this.
If I'd call some C# functions, I'd like to call like this
```
Execute Game.Player.Character.Kill()
```

**Comment by kagikn** [comment]
Now we can reload all scripts with one command, just like v2, yes.

**Pull request merged**
