### PR TITLE
Introduce interfaces

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Good idea, although I don't think we need an 'interface' folder, the leading I should be enough. 

(But that's just my opinion, @crosire propably knows best :D)

**Comment by kagikn** [comment]
I was inspired by the interfaces in RAGE Plugin Hook, and now I realized that interfaces are useful.

**Comment by RainerHilmer** [comment]
I am a professional software developer and I have never seen interfaces being in a subfolder. Having it this way means having to reference a sub-namespace, which is not advised in such a case.

**Comment by crosire** [comment]
Interfaces are a very nice feature, but I'm not convinced they are useful in this case. What advantages does it give us here? It's not less code, even more actually.

**Comment by kagikn** [comment]
Example

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
using GTA;
using GTA.Native;
using GTA.Math;

namespace Example
{
	public class GetDistance2D: Script
    {
        
        public GetDistance2D()
	{
			Tick += OnTick;
			Interval = 0;
	}

        void OnTick(object sender, EventArgs e)
        {
            var player = Game.Player.Character;
            if (player == null || !player.Exists()) { return; }

            var dist = Distance2D(player, World.RenderingCamera);

            UIContainer mContainer2 = new UIContainer(new Point(0, 0), new Size(500, 80));
            mContainer2.Items.Add(new UIText(dist.ToString(), new Point(0, 0), 0.5f, Color.White, GTA.Font.ChaletLondon, false, true, false));
            mContainer2.Draw();
        }

        private float Distance2D(ISpatial from, ISpatial to)
        {
            return Vector3.Distance2D(from.Position, to.Position);
        }
    }
}
```

**Comment by crosire** [comment]
But the same can be achieved with the same amount of code:
```
namespace Example
{
    public class GetDistance2D: Script
    {

        public GetDistance2D()
        {
            Tick += OnTick;
            Interval = 0;
        }

        void OnTick(object sender, EventArgs e)
        {
            var player = Game.Player.Character;
            if (player == null || !player.Exists()) { return; }

            var dist = Distance2D(player.Position, World.RenderingCamera.Position);

            UIContainer mContainer2 = new UIContainer(new Point(0, 0), new Size(500, 80));
            mContainer2.Items.Add(new UIText(dist.ToString(), new Point(0, 0), 0.5f, Color.White, GTA.Font.ChaletLondon, false, true, false));
            mContainer2.Draw();
        }

        private float Distance2D(Vector3 from, Vector3 to)
        {
            return Vector3.Distance2D(from, to);
        }
    }
}
```

**Comment by JohnnyCrazy** [comment]
Let's say we want to keep track of some objects' positions. We could create a `List<ISpatial> _keepTrack` and check them frequently. Without those interfaces, there is no proper way to do it AFAIK.

(The advantages are very particular indeed, but I don't see any disadvantages)

**Comment by crosire** [comment]
I agree with IHandleable. But ISpatial and IRotatable should be merged into one. I also don't think we need an IEquatable. I'm with @JohnnyCrazy on the "interface" folder being uncessary, even simpler would be to put them all into one file (since the interface declarations only take a few lines each).

**Comment by kagikn** [comment]
Apparently, implementing IEquatable can improve performance when using it with generics.
http://stackoverflow.com/questions/2734914/whats-the-difference-between-iequatable-and-just-overriding-object-equals

**Comment by crosire** [comment]
Alright.

**Comment by kagikn** [comment]
Interface hpp files were merged into one.

**Pull request merged**
