### PR TITLE
Add Texture Coordinates to sprite class

### PR DESCRIPTION
**Pull request by NiziulLuizin**

### CODE REVIEW

**Review by kagikn — CHANGES_REQUESTED** [review]
The 2 constructor overloads should be kept, which are `Sprite(string textureDict, string textureName, SizeF size, PointF position, Color color, float rotation)` and `Sprite(string textureDict, string textureName, SizeF size, PointF position, Color color, float rotation, bool centered)`.

**Comment by kagikn** [comment]
I mean, adding overloads are welcome, but overloads should not be deleted if some public release contain them.
Also, adding new public features or overloads must be also reviewed by the owner @crosire . This repo doesn't say that, but that's the rule.

**Comment by NiziulLuizin** [comment]
> I mean, adding overloads are welcome, but overloads should not be deleted if some public release contain them. Also, every new features that adds new public features or overloads must be reviewed by the owner @crosire . This repo doesn't say that, but that's the rule.

I understand. About my review request, that was a mistake, I ended up clicking on something I shouldn't have, sorry.

**Comment by crosire** [comment]
This seems to be deleting the `Sprite(string textureDict, string textureName, SizeF size, PointF position, Color color, float rotation)` constructor by accident still.

**Review by kagikn — APPROVED** [review]
LGTM now as there's no name change request.

**Pull request merged**
