### PR TITLE
Added first UI-Classes and a basic component system

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
Result of the discussion in #8 

Features:
* Basic Component-System (`UIContainer` can contain unlimited `UIElement`s))
* Following UI Elements: `UIText`, `UIRectangle` and `UIContainer` (UIContainer implements UIRectangle)
* New InputArgument constructor (`const char[]`)

We offer users a 1280:720 coordinate-system so it's a lot easier to create nice looking GUIs. internally, they get converted to the relative coordinates.

Basic example:
````c#
//colors
private Color titleColor = Color.WhiteSmoke;
private Color headerColor = Color.FromArgb(255, 26, 188, 156);
private Color bodyColor = Color.FromArgb(200, 237, 239, 241);
private Color selectColor = Color.FromArgb(135, 26, 187, 155);
private Color textColor = Color.Black;
private UIContainer container;

//Constructor of your script e.g
container = new UIContainer(new Point(10, 240), new Point(200, 300), bodyColor);
container.Items.Add(new UIRectangle(new Point(0, 0), new Point(200, 30), headerColor));
container.Items.Add(new UIText("Vehicle Spawner", new Point(100, 4), 0.5f, titleColor, 4, true));
container.Items.Add(new UIRectangle(new Point(0, 30), new Point(200, 30), selectColor));
container.Items.Add(new UIText("Test", new Point(100, 34), 0.4f, textColor, 0, true));

//OnTick-Event
container.Draw();

//OnKeyDown
if (e.KeyCode == Keys.I) //Toggle Draw
    container.Enabled = !container.Enabled;
````
img

### CODE REVIEW

**Comment by Monsterxsync** [comment]
Very nice. clean and simple. love it

**Comment by StijnBrouwer** [comment]
Nice! But it looks like you don't have a way to handle events in the elements themselves, so you need to manage the handling of events separate from the GUI classes. Not that that's bad, but you'd need a simple way to set elements as focused. I think this is a great start though. I might try and work on some abstractions to make the creation of menus easier.

BTW, you typo'ed `source/UiElement.h`.

**Comment by Monsterxsync** [comment]
found one issue that alot of players will have.. you NEED to have v-sync enabled for this to work

**Comment by JohnnyCrazy** [comment]
@Monsterxsync  
Are you sure about this? Will test it later

@StijnBrouwer  
What do you mean excatly with events? Like Click/focus events?
Focus is currently handled by the order they got added to the container

**Comment by Monsterxsync** [comment]
@JohnnyCrazy 
Sorry it was my mistake the Interval needs to be set to 0 if V-sync is enabled.

**Comment by crosire** [comment]
Nice job!
About "Interval". Setting it to zero runs the Tick event every frame, which is what is needed for the drawing to appear, otherwise it would only draw every X ms and thus flicker.

**Comment by JohnnyCrazy** [comment]
@crosire 
If V-Sync is on, a 10 Tick interval seems to be fine strangely...

**Comment by crosire** [comment]
@JohnnyCrazy Because V-Sync forces the game to render only 30-60 frames a second, depending on your monitor sync speed. 10ms is then faster than a game frame (~33ms), so no frame is skipped and everything runs fine.

**Comment by Monsterxsync** [comment]
how would i go about indexing each menu item? so i can simply use the numpad to add and take from the index to select.

**Comment by JohnnyCrazy** [comment]
@Monsterxsync  
You could use a `Dictionary<int, UIText>` and add elements to the container on creation

**Comment by Monsterxsync** [comment]
thanks will try in a bit.

**Comment by crosire** [comment]
I hope you don't mind me adjusting the code a little to the style the rest of the codebase uses: 90bb1b41c70b98a963d1bb92cea6d10a1e195b17. =)
Also replaced "System::Drawing::Point" type of the "Size" property with "System::Drawing::Size", makes more sense in my opinion.

**Comment by JohnnyCrazy** [comment]
Yea sure :+1:

**Comment by StijnBrouwer** [comment]
@JohnnyCrazy Yeah, that's what I mean. For example, handling which element is highlighted in a menu when you use numpad 8 and 2, can only really be handled by outside code. Like @Monsterxsync said.

**Comment by JohnnyCrazy** [comment]
Yea, but IMO we actually should create Menu-Wrappers outside of the base, not directly into it. We can continue the discussion in #8 if you want :+1:

**Pull request merged**
