### PR TITLE
SetVehicleMod, GetVehicleMod, SetColors, GetColors, PrimaryColor, SecondaryColor

### PR DESCRIPTION
**Pull request by IncoCode**
Colors hashes taken from: http://gtaforums.com/topic/788275-models-color-hashes/
Some example:
```c#
Ped player = Game.Player.Character;
if ( player.IsInVehicle() )
{
	Vehicle veh = player.CurrentVehicle;
	switch ( veh.GetMod( VehicleModName.Spoilers ) )
	{
		case 1:
			veh.SetMod( VehicleModName.Spoilers, 2, true );
			veh.PrimaryColor = VehicleColors.MatteBlue;
			veh.SecondaryColor = VehicleColors.MatteOrange;
			break;

		case 2:
			veh.SetMod( VehicleModName.Spoilers, 1, true );
			veh.PrimaryColor = VehicleColors.HotPink;
			veh.SecondaryColor = VehicleColors.MetallicGreen;
			break;

		default:
			veh.SetMod( VehicleModName.Spoilers, 1, true );
			break;
	}
}
```

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Nice!

Do you mind changing `Colour` to `Color`? So we don't have different Colo(u)rs in our script :smile:

**Comment by crosire** [comment]
I'd suggest to use two properties (Color1 and Color2) instead of the getter and setter functions, since the address operator requires to enable unsafe code under C# and doesn't work with VB.Net at all (though instead we could use reference arguments too). Also, note the "Color", do you mind if we use the "o" instead of "ou" notation? What do you think?

**Comment by Nacorpio** [comment]
This looks really nice.
I have many ideas for mods in the future, which will include pre-modified vehicles.

Thank you!

**Comment by Monsterxsync** [comment]
The natives use colour.

**Comment by crosire** [comment]
@Monsterxsync: Which is why I first thought GTAV had no way to change the vehicle color anymore, until I stumbled on them by accident.

**Comment by IncoCode** [comment]
Native name is SET_VEHICLE_COLOURS, so that's why i have used "ou" :smile: But anyway i already  changed it to "o"
Also added properties PrimaryColor and SecondaryColor and GetMod method.

**Comment by Nacorpio** [comment]
I really think this update should be pushed as soon as possible.
I'm very excited to start playing around with it.

**Comment by Nacorpio** [comment]
Niiiiiice.

**Pull request merged**
