### PR TITLE
Made World.GravityLevel a float property instead of Enum

### PR DESCRIPTION
**Pull request by zorg93**
Added Bennys wheel types to WheelType Enum
Added Allowed wheel types property to Mods class
Added LocalizedWheelTypeName to Mods class
Added DoesGXTLabelExist to Game class

### CODE REVIEW

**Comment by Fireboyd78** [comment]
You think this is compatible with previous game versions?

**Comment by zorg93** [comment]
It was made from reversing the 335 game version, then checked on the 757 version. I'm guessing it should work on all version

**Comment by zorg93** [comment]
Changed Matrices class to use SIMD instructions to improve performance and make the code a bit cleaner

**Comment by zorg93** [comment]
Added many more changes @crosire @JohnnyCrazy thoughts?

**Comment by JohnnyCrazy** [comment]
Besides:
> source\scripting\Vector3.cpp(23): error C2448: 'alignas' : function-style initializer appears to be a function definition
, how is future compatability compared to the native? Do you think the pattern will change sometime soon? IMO we should keep memory-operations as little as possible for the sake of future compatability.

**Comment by zorg93** [comment]
@JohnnyCrazy It compiles in visual studio, I could replace it and just use the unaligned load.
The worldGravity doesnt have a native equivalent and the signature hasnt changed from 335 to 757. As for the bone and entity matrix. Those parts of the entity structure have also remained unchanged since 335(probably the version before that, but I dont have a copy of the exe to check)

**Comment by zorg93** [comment]
well I removed the error

**Comment by JohnnyCrazy** [comment]
LGTM then @crosire  :)

**Comment by crosire** [comment]
`alignas(16)` is C++11, Visual C++ 2013 does not recognize it. Simply use `__declspec(align(16))` instead.

**Comment by zorg93** [comment]
ahh, I've been compiling it in 2015, anyway I solved the issue by using loadu

**Comment by crosire** [comment]
It's not a comparable solution. loadu is much slower than load with the data aligned correctly.

**Pull request merged**
