### PR TITLE
Fix control methods

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by leonardosnt** [comment]
what need it?

all methods work perfectly

**Comment by kagikn** [comment]
Ah, I thought EnableControl and DisableControl aren't included in any release version. I'll add Obsolete attribute for them again.

**Comment by kagikn** [comment]
Okay, I added Obsolete attribute again.

**Comment by leonardosnt** [comment]
@kagikn Because was wrong, i wrote the IsDisabledControlPressed ... etc and just ctrl+c ctrl+v to avoid rewriting again the IsControlPressed, and i just changed the method name, but, i forgot to change native name.

You need know that:
IS_DISABLED_CONTROL_PRESSED != IS_CONTROL_PRESSED

**Comment by kagikn** [comment]
@leonardosnt I know that:
IS_CONTROL_PRESSED == (IS_DISABLED_CONTROL_PRESSED && IS_CONTROL_ENABLED)

**Comment by leonardosnt** [comment]
```c#
Game.DisableControl(0, Control.Cover );

UI.ShowSubtitle(
    Game.IsDisabledControlPressed(0, Control.Cover ) + " " + 
    Game.IsControlPressed(0, Control.Cover )
);
```


@kagikn But why call 2 natives if you can call only one? its make no sense.

**Comment by kagikn** [comment]
@leonardosnt Because there is no way to detect if a "disabled" control is pressed with only one native, different from enabled control.

**Comment by leonardosnt** [comment]
@kagikn why not??

Game.IsDisabled* works perfectly

See my post above

**Comment by kagikn** [comment]
@leonardosnt current Game.IsDisabled* don't detect if a controls is disabled. Script writers should expect Game.IsDisabled* detect if a control is disabled and pressed(or just pressed or just released), don't they?

**Comment by crosire** [comment]
I do agree with @kagikn. This behavior is more obvious.

**Comment by leonardosnt** [comment]
Your code does exactly same thing, but calling 2 natives, it's ridiculous.

But this isn't my project, do what you want.

**Comment by leonardosnt** [comment]
I agree with function In Control Enabled, but the anothers is ridiculous, already have an native that do it, there no reason to call 2 natives.

**Comment by crosire** [comment]
The code doesn't do the same thing. "IsControlPressed" now always returns whether a control is pressed, regardless of it being enabled or disabled. "IsDisabledControlPressed" now only returns true if the control is pressed and it is disabled. It will always return false if the control is enabled. Same for "IsEnabledControlJustPressed", just the other way round.

**Comment by kagikn** [comment]
So @crosire, will you merge this?

**Pull request merged**
