### PR TITLE
Updated Euphoria for the latest patch

### PR DESCRIPTION
**Pull request by CamxxCore**

### CODE REVIEW

**Comment by Nacorpio** [comment]
Me and jedijosh920 has try to build the version you sent on GTAForums, and that one didn't work properly. Is it confirmed to be working now?

**Comment by Nacorpio** [comment]
Alright, it works.
Thank you for your effort, even though it only was an offset by 16. 

LOL.

**Comment by CamxxCore** [comment]
Happy to help. For future reference, just look at the GiveNmMessage function. All offsets are there

**Comment by crosire** [comment]
Nice one :smiley:

**Comment by zorg93** [comment]
Would it not be a idea to leave the country old patch support and use a game version check

**Comment by zorg93** [comment]
Don't know how country appeared on the comment

**Comment by crosire** [comment]
@zorg93 In theory yes, in praxis I can't think of many reasons to continue supporting older patches. Then again, the lowrider update patch code does check for the required game version before applying too. So yeah. I guess it wouldn't hurt?

**Comment by zorg93** [comment]
Does anyone know which version euphoria stopped working on?

**Comment by kagikn** [comment]
It stopped working on since 1.0.573.1, that's for sure.

**Pull request merged**
