### PR TITLE
Add more logic for how to resolve different SHVDN versions

### PR DESCRIPTION
**Pull request by udoprog**
So I wasn't able to use this project with a mixed set of plugins. The loader failed to load a mod I've downloaded off the internet with the following:

```
[20:47:37] [DEBUG] Loading assembly Metric_Speedometer.dll ...
[20:47:37] [WARNING] Unable to resolve API version 0.0.0 used in ScriptHookVDotNet.
```

Basically, somehow they've managed to reference `ScriptHookVDotNet` with a version of `0.0.0` when building. This patch adds a special check for that where it picks up the last major version 2 of the api that was discovered.

I've also added logic for picking the "best" major version when multiple versions are available and a bit more diagnostics of the assembly that requested the dependency (`RequestingAssembly`).

Additionally, it seems like the resolver fails if it logs anything during the initial loading from the `.asi`. I tried to add a `DEBUG` statement to the top of the `HandleResolve` function, but it errored on me.

### CODE REVIEW

**Comment by crosire** [comment]
Thank you! I've taken your changes but changed formatting a bit (still kept you as author, hope you don't mind).

**Comment by udoprog** [comment]
@crosire Thanks. you seem to have missed the case where we match against version `0.0.0` to API major version `2`:
https://github.com/crosire/scripthookvdotnet/pull/881/files#diff-f65f016669ee9c7c3a1c514c0245e816R752

**Comment by crosire** [comment]
Nope: https://github.com/crosire/scripthookvdotnet/commit/362bddcb2f8c2a8e3c875067d12be1d378f8a2c0#diff-f65f016669ee9c7c3a1c514c0245e816R724

**Comment by udoprog** [comment]
Ah, yeah missed that. All right, I'll test it out.

**Pull request closed without merging**
