### PR TITLE
Fixed Game::GetUserInput. Added WindowTitle enum.

### PR DESCRIPTION
**Pull request by LibertyLocked**
Fixed window title for onscreen keyboard.

### CODE REVIEW

**Comment by crosire** [comment]
I wouln't remove the "GetUserInput(System::String ^defaultText, int maxLength)" overload, or we will break existing scripts. It should just forward the call to the overload with WindowTitle param set to FMMC_KEY_TIP8.

**Comment by LibertyLocked** [comment]
I've added it back and marked obsolete.

**Comment by crosire** [comment]
But it now doesn't do what it originally was supposed to do, which was provide default/start text, not the window title ...

**Comment by LibertyLocked** [comment]
Sorry I must have misread it. Thanks for catching that.

**Comment by IncoCode** [comment]
Did you test it? Because after this update i cannot enter any data in the field. Text field just contains  default text and I even cannot delete it.
```c#
Game.GetUserInput( "Enter value...", 9 );
```

**Comment by LibertyLocked** [comment]
I think it's because your max length is less than the length of "Enter value..."?

**Comment by IncoCode** [comment]
As far as I remember in some of previous versions this text was a window title or not? :confused:

**Comment by LibertyLocked** [comment]
I don't think the window title in the previous version works at all. In fact, the string is supposed to be "start text" but was used incorrectly as "window title". Window title is an enum in GAMEPLAY::DISPLAY_ONSCREEN_KEYBOARD.

**Comment by JohnnyCrazy** [comment]
@LibertyLocked just to make it clear: We can't create custom window titles.

**Comment by IncoCode** [comment]
Oh, okay, sorry. :confused:

**Pull request merged**
