### PR TITLE
Scaleforms

### PR DESCRIPTION
**Pull request by mlgthatsme**
# Scaleforms class for loading and rendering Scaleforms.

**Small Example:**
```
-- Initialize
Scaleform FloatingText = new Scaleform();
FloatingText.Load("PLAYER_NAME_01");

-- In Tick Event
FloatingText.CallFunction("SET_PLAYER_NAME", "Swag L0rd");
FloatingText.Render3D(Game.Player.Character.Position + new GTA.Math.Vector3(0, 0, 2.5f), new GTA.Math.Vector3(), new GTA.Math.Vector3(6, 3, 1));

```

To find more functions, you have to open the GFX files in the game using a program like **JPEXS**

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Wow, this will be awsome for modders, good job! :+1: 

BTW, is there any list of supported functions floating around? Maybe we could provide an enum or sth like that.

**Comment by mlgthatsme** [comment]
There isn't a list, but I can put one together. But like in my comment, modders can just extract the GFX Files and call the functions that JPEXS gives them. I'll make a doc on it eventually.

**Comment by Nacorpio** [comment]
Can you upload a screenshot on what this looks like, @mlgthatsme?

**Comment by JohnnyCrazy** [comment]
Anyway, merging :)

**Comment by mlgthatsme** [comment]
I made a blog post here, it's what you see floating above the cars. Those are scaleforms.

https://www.mlgthatsme.com/mods/gta-v-single-player-garage-script/

**Comment by Nacorpio** [comment]
That is impressive. How do you customize these with the different type of controls?

**Comment by mlgthatsme** [comment]
Im not sure I know what you mean?

**Comment by Nacorpio** [comment]
Well, there is a bunch of different components within each scaleform.

**Comment by mlgthatsme** [comment]
Oh right. Well a Scaleform is just a flash video with action script. Each one contains their own functions, for instance the vehicle status one has "setBar(index, value)". Calling that function will set the bars values. Then you just have to render it, and thats it. Hope that explains it.

**Comment by JohnnyCrazy** [comment]
@mlgthatsme 
Just tried your example but I'm unable to see anything rendered
````c#
//Ctor
form = new Scaleform();
form.Load("PLAYER_NAME_01");

//Tick
form.CallFunction("SET_PLAYER_NAME", "Swag L0rd");
form.Render3D(Game.Player.Character.Position + new Vector3(0, 0, 2.5f), new Vector3(), new Vector3(6, 3, 1));
````

But this kinda half works?
````c#
//ctor
form = new Scaleform();
form.Load("MP_VEHICLE_INFO");
//tick
form.CallFunction("SET_TITLE", "What is this?");
form.CallFunction("SET_DESCRIPTION", "That's a nice description");
form.Render3D(playerPed.Position + (playerPed.ForwardVector * 0.4f), playerPed.Rotation, new Vector3(6, 3, 1));
````
img

**Comment by JohnnyCrazy** [comment]
It seems like a restart fixed it...strange tho.

**Comment by mlgthatsme** [comment]
Never gotten that problem before...

**Pull request merged**
