### PR TITLE
Added some natives

### PR DESCRIPTION
**Pull request by UnknownModder**

### CODE REVIEW

**Comment by UnknownModder** [comment]
For some reason I made a mistake at line 6209 (redefinition), please remove this line.

**Comment by Fireboyd78** [comment]
Nice! However I noticed you removed quite a few natives -- may I suggest adding a `System::Obsolete` attribute to them instead? I imagine we'll plan ahead of time when to stop supporting backwards compatibility for existing mods (if ever).

**Comment by crosire** [comment]
Yeah, updates should only add new values to the ```Hash``` enum, never remove any.

**Comment by UnknownModder** [comment]
Updated again:
- Removed _REQUEST_SCALEFORM_MOVIE2 as it's the same as REQUEST_SCALEFORM_MOVIE_INSTANCE (same hash)

- Renamed _IS_OUTFIT_EMPTY to _IS_DLC_DATA_EMPTY as this is the actual use of this native

- Added _SET_PLAYER_INVINCIBLE_RAGDOLL_ENABLED (0x733A643B5B0C53C1)

**Comment by crosire** [comment]
@UnknownModder There could be scripts references either one of them, even if they refer to the same hash. Removing it would break those scripts.
The pull request still removes ```_REQUEST_SCALEFORM_MOVIE2``` and ```_IS_OUTFIT_EMPTY```.

**Comment by UnknownModder** [comment]
@crosire If you say so, readded them. (Ich persönlich denke zwar kaum, dass irgendjemand diese Natives überhaupt nutzt, aber naja, was soll's)

**Comment by crosire** [comment]
@UnknownModder I don't think so either, but minor releases guarantee backwards compatibility. We can clean these up in the next major release (3.0).

**Pull request merged**
