### PR TITLE
Updated the list of Natives for v2

### LINKED ISSUE #879: Update Native Hash List
There's a few missing native hashes as well as wrong hashes for some items.

for example **0xD80A80346A45D761** aka _GET_SCALEFORM_MOVIE_METHOD_RETURN_VALUE_BOOL
https://unknownmodder.github.io/gta5-native-db/
vs
http://www.dev-c.com/nativedb/
another example is SITTING_TV native is GET_SCALEFORM_MOVIE_METHOD_RETURN_VALUE_STRING

Unsure of how many missing items there are in total but one I've used recently is **0xB4771B9AAF4E68E4** aka _SET_CAN_PED_EQUIP_WEAPON

To work around I've been converting these like so:
var _SET_CAN_PED_EQUIP_WEAPON = (Hash)0xB4771B9AAF4E68E4;

### PR DESCRIPTION
**Pull request by justalemon**
Let me know if I broke something.

Closes #879

### CODE REVIEW

**Comment by justalemon** [comment]
I was not able to set this PR as a Draft, so please wait until I update the rest of them.

**Comment by Tanjitsu** [comment]
Might be a good time to move Natives to the Source and then add access for both v2 and v3 branch to work from one list. The game only needs one set of Natives, it seems crazy to be maintaining 2.

**Comment by justalemon** [comment]
I agree. If you guys find a way to store the natives for both versions I can send a PR to update them.

**Comment by crosire** [comment]
v2 needs a separate list for backwards compatibility. It still has `_0x123456789` entries in the enum that are used in the wild. In v3 we got rid of those in favor of casting. We cannot remove any existing entries in v2 without breaking all scripts that use them. Only add new ones. v3 is still frer from that burden because not officially released, so no backwards compatibility to maintain.

**Comment by Tanjitsu** [comment]
If the Csharp port of V2 is viable we should be able to use the V2 Native Hash list for both V2 and V3.

**Comment by crosire** [comment]
@Tanjitsu The port works for the most part but has one issue that breaks it currently: https://github.com/crosire/scripthookvdotnet/issues/869#issuecomment-520260653

**Comment by justalemon** [comment]
So, little problem. On SHVDN I have:

```cpp
_0x2B7E9A4EAAA93C89 = 0x2B7E9A4EAAA93C89,
_0x1CCD9A37359072CF = 0x1CCD9A37359072CF,
_SET_NOTIFICATION_MESSAGE = 0x1CCD9A37359072CF,
_0xC6F580E4C94926AC = 0xC6F580E4C94926AC,
_0x1E6611149DB3DB6B = 0x1E6611149DB3DB6B,
```

But on Unknown's Native Database I have:

```cpp
static int _SET_NOTIFICATION_MESSAGE(const char* picName1, const char* picName2, BOOL flash, int iconType, BOOL p4, const char* sender, const char* subject) { return invoke<int>(0x2B7E9A4EAAA93C89, picName1, picName2, flash, iconType, p4, sender, subject); } // 0x2B7E9A4EAAA93C89 0xED130FA1 b323
static int _SET_NOTIFICATION_MESSAGE_2(const char* picName1, const char* picName2, BOOL flash, int iconType, const char* sender, const char* subject) { return invoke<int>(0x1CCD9A37359072CF, picName1, picName2, flash, iconType, sender, subject); } // 0x1CCD9A37359072CF 0xE7E3C98B b323
static int _SET_NOTIFICATION_MESSAGE_3(const char* picName1, const char* picName2, BOOL flash, int iconType, const char* sender, const char* subject) { return invoke<int>(0xC6F580E4C94926AC, picName1, picName2, flash, iconType, sender, subject); } // 0xC6F580E4C94926AC b323
static int _SET_NOTIFICATION_MESSAGE_4(const char* picName1, const char* picName2, BOOL flash, int iconType, const char* sender, const char* subject, float duration) { return invoke<int>(0x1E6611149DB3DB6B, picName1, picName2, flash, iconType, sender, subject, duration); } // 0x1E6611149DB3DB6B 0x0EB382B7 b323
```

What should be done on this case? How should I name them?

**Comment by justalemon** [comment]
CC @crosire @Tanjitsu

**Comment by crosire** [comment]
I'd keep them as they were in v2 and fix them in v3 later.

**Comment by justalemon** [comment]
I'm closing this because the merge of the C# version of v2 broke the list of natives and I'm not going to check every single one of them manually again.

**Comment by crosire** [comment]
Please also note that we actually have an automated process to generate this enum: Run the "NativeGen" target in Visual Studio and it will update the v3 list to the latest version from nativedb.

**Comment by justalemon** [comment]
A couple of problems with that:

* It uses NativeDB, that has been outdated for approx. 2 years (one of the reasons why I'm using the native list by @UnknownModder )
* The code generated is for v3, not v2
  * Copy/Pasting the values on v2 is not possible without breaking backwards compatibility

**Comment by crosire** [comment]
I can update the NativeGen tool to poll from https://github.com/UnknownModder/gta5-nativedb-data/raw/master/natives.json instead of nativedb. But I think it makes sense to keep this process automated as much as possible, since it's a pretty huge list to maintain manually otherwise. Could also change the tool to support some options to generate the appropiate lists for v2 or v3.

**Pull request closed without merging**
