### PR TITLE
Fix typo of StopAllBehavioursHelper

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by crosire** [comment]
Oh. Seems like my regex comment fixup changed a bit too much 😄.

**Comment by kagikn** [comment]
Ah, you're right. I changed a bit too much.

**Comment by kagikn** [comment]
Sorry, but I made a PR (#704) and merged the PR to fix the comment.

**Comment by crosire** [comment]
Btw. you have push access to this repo, so for this small of a fix, just push the commit directly without going through the trouble of creating a pull request for it.

**Comment by kagikn** [comment]
I thought the 2 dev branches are also protected, as well as the master branch.

**Comment by crosire** [comment]
They are protected against force pushes to avoid somebody accidently overwriting something. But a normal push is still possible.

**Comment by kagikn** [comment]
Before I can push commits to the master branch, I had to make a new branch (or make a pull request) and wait for AppVeyor until the check was passed, though.

**Comment by crosire** [comment]
Yeah, the master branch is a different from the dev branches. It's protected even more.

**Pull request merged**
