### PR TITLE
Ped + Game Addition

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
Just two small additions. @crosire 

(Thanks to @XBLToothPik for finding it!)

### CODE REVIEW

**Comment by XBLToothPik** [comment]
Good stuff.  The only thing that is wrong is that on GET_NIGHTVISION, it returns TRUE if nightvision is NOT active.  Not if it is active.

**Comment by LibertyLocked** [comment]
Would be nice if you name the hash _GET_PED_KILLER in NativeHashes

**Comment by crosire** [comment]
Jup, I'd fix both the two things @XBLToothPik and @LibertyLocked mentioned before merging.

**Comment by JohnnyCrazy** [comment]
Will do it when i'm at home.

(Wouldnt it be better if we update all hashes at the same time? This would break all scripts once, but not each commit :P )

**Comment by crosire** [comment]
I'm fine with things breaking each commit as long as it's in the unstable working branch. Releases shouldn't do that obviously, unless they increase the major version number.

**Comment by JohnnyCrazy** [comment]
@XBLToothPik 
`_GET_IS_NIGHTVISION_ACTIVE` returns normal values like it should? Are you sure about that? Also tested it.

Hashes are named now :)

**Comment by crosire** [comment]
Does Ped::GetKiller really return a prop in some cases?

**Comment by JohnnyCrazy** [comment]
Asked it a day ago in the skype-dev group, they said yes.

**Comment by JohnnyCrazy** [comment]
After some heavy ped + prop spawning, I successfully killed one with a prop and the killer was the actual prop :D 
img

@crosire

**Comment by crosire** [comment]
Alright!

**Pull request merged**
