### PR TITLE
Added new property MaxHealth for Peds instead of using Entity MaxHealth

### PR DESCRIPTION
**Pull request by zorg93**
Fix for #266

### CODE REVIEW

**Comment by tcpie** [comment]
Shouldn't we use value + 100 in the setter and -100 in the getter, just as in entity.cpp?

**Comment by crosire** [comment]
And make the properties virtual, so the Entity one is properly overwritten?

**Comment by zorg93** [comment]
You don't need to make it virtual for it to be overwritten and why do we even add 100 to the max health property???

**Comment by crosire** [comment]
I'm pretty sure you do, so the following works correctly:
```c#
Entity e = new Ped(); e.MaxHealth = 100;
```

**Comment by zorg93** [comment]
Ahh ok I'll update that, will be next week though as going away again tonight. Unless you want to put it in instead

**Comment by crosire** [comment]
Alright, I'll do it then =).

**Comment by zorg93** [comment]
I'll close this then =D

**Pull request closed without merging**
