### PR TITLE
Added blip sprite ids to enum for easier accessibility

### PR DESCRIPTION
**Pull request by Frede1012**

### CODE REVIEW

**Comment by Frede1012** [comment]
This took way to long... :-(

**Comment by mlgthatsme** [comment]
You legend! Exactly what I needed!

**Comment by Nacorpio** [comment]
Thank you man. I really need this shit.

**Comment by Frede1012** [comment]
Hehe, no problem guys! :)

@JohnnyCrazy @crosire

**Comment by JohnnyCrazy** [comment]
Woob woob :+1:

**Comment by JohnnyCrazy** [comment]
BTW, we should change the property `Sprite` to the new enum @Frede1012

**Comment by Frede1012** [comment]
@JohnnyCrazy I was just thinking about that. Do you want me to do that?

**Comment by JohnnyCrazy** [comment]
Sure, if you want to, else I will do it later :)

**Comment by Frede1012** [comment]
@JohnnyCrazy Gimme a sec, i will send a pull request :)

**Comment by Frede1012** [comment]
@JohnnyCrazy Done #138

**Pull request merged**
