### PR TITLE
Fixed Issue #862

### PR DESCRIPTION
**Pull request by Cr1TiKa7**
Fixed Issue #862 and added the Function GetEntryPositionOfDoor to the Vehicle class and the Property GetEntryPosition to the VehicleDoor class

### CODE REVIEW

**Comment by Cr1TiKa7** [comment]
I also added now the ability to add an Attribute to the Script to specify the required version of scripthookvdotnet #449

**Comment by Tanjitsu** [comment]
You can reload the script by using F3 for the console, then type "ReloadAllScripts()" or "Reload(string filename)" see [Console.cs](https://github.com/crosire/scripthookvdotnet/blob/dev_v3/source/core/Console.cs)

**Comment by Cr1TiKa7** [comment]
Oh didn't noticed that. But they can still skip this commit even tho I still prefer to reload the scripts by keypress.

But thank you for telling me this!

**Comment by Tanjitsu** [comment]
You might be better to break your changes into individual commits.
This way people can discuss / accept or reject them individually rather than one or nothing.

Your reload by key was removed from svdnV3 so i don't think it will get re-added. yet the GetEmptySeat functions could be an easy accept as an addition rather then a change.

**Comment by kagikn** [comment]
This PR is too fucking big and has too many changes that is not related to #862, making it difficult to review. Please create PRs that have enough consistency to review. I'll close this one.

**Pull request closed without merging**
