### PR TITLE
Tweaked how GetEntityPool works

### PR DESCRIPTION
**Pull request by zorg93**
This needs a bit of work before merging as it will break compiled scripts that use World.GetAll/GetNearby methods but Im not sure on the best way to implement it

### CODE REVIEW

**Comment by Nacorpio** [comment]
Why is this any better than the previous method?

**Comment by crosire** [comment]
It gives more control on the type of models. Though it's probably best to introduce this behavior as new overloads/methods rather than replacing the existing ones.

**Comment by zorg93** [comment]
The issue i had is using params for the models means i cannot overload the functions as the functions signature will be too similar. If this was saved for a 3.0 release all people would need to do is recompile against a new sdk

**Comment by zorg93** [comment]
@Nacorpio the change means that to find via using multiple models like  World.GetAllVehicles(new model(VehicleHash.Buffalo), new model(VehicleHash.Buffalo2));

**Comment by Nacorpio** [comment]
Wouldn't that type of behavior slow down the function significantly?

**Comment by zorg93** [comment]
Its implemented early on enough that it shouldnt slow down the function noticeably.

**Comment by Nacorpio** [comment]
I have been wanting something similar, I was just afraid that it was going to decrease the performance by a lot.

**Comment by zorg93** [comment]
Maybe if you check each entity against a massive list of hashes it may have a perceivable drop in performance but to only check a couple of models it's like an extra 10 instruction cycles which is nothing compared to the time it takes to get each pool item

**Comment by JohnnyCrazy** [comment]
Since we plan to break stuff with 3.0 anyway, I think it would be a good opportunity to introduce this new behavior

**Comment by crosire** [comment]
Merged into ```dev_v3``` in e063163b6a8b233024a68019ff8579c12ff483a6.

**Pull request closed without merging**
