### PR TITLE
Renamed MarkerTypes to MarkerType, Made HandleViewportInput overridable

### PR DESCRIPTION
**Pull request by Frede1012**

### CODE REVIEW

**Comment by zorg93** [comment]
This doesnt really make much sense, if all the menu default controls are on the numpad, having the back button not on there seems wrong

**Comment by JohnnyCrazy** [comment]
Agree, I suggest `NumPad1`

**Comment by crosire** [comment]
It was suggest because GTA uses the back button to go back by default too. But you're right, NumPad0 actually makes more sense currently since all other controls are on numpad too.

**Comment by Frede1012** [comment]
Its also the control scheme used by the native trainer that is bundled with the scripthook. And therefor probably the control scheme people are gonna be used to :-)

**Comment by frodzet** [comment]
I strongly disagree, having 0 as a back key makes no sense to me. I understand the logic of having NumPad8, 2 up/down, 4,6 left/right and 5 as activate. If any numpad key i think NumPad7 (Home) or NumPad1 (End) as their non-numlock function is Home and End, but i'm just weird about such stuff :-D

**Comment by Frede1012** [comment]
Isn't having the key be the same as for other menus bundled with the best idea?

**Comment by crosire** [comment]
Yeah. And Numpad0 is very useful as the back key, because that's where your thumb lies on when navigating with the other keys. So one can use the whole menu without moving the hand once.

**Comment by Frede1012** [comment]
Thats not what i meant, if other menus (the native trainer) are already using backspace, shouldn't we be too?

**Comment by crosire** [comment]
The native trainer uses Numpad0?!

**Comment by Frede1012** [comment]
What?? I have been using backspace all along?

**Comment by Frede1012** [comment]
Nevermind then, i have reverted the key change :)

**Pull request merged**
