### PR TITLE
Added font enum

### PR DESCRIPTION
**Pull request by Frede1012**

### CODE REVIEW

**Comment by nevadascout** [comment]
Looks good, but I believe the Item and Footer fonts are Helvetica, not Arial.

**Comment by Frede1012** [comment]
@nevadascout How come? The old value was 0?

**Comment by nevadascout** [comment]
My bad, just checked the interaction menu in-game -- they are Arial xD

**Comment by zorg93** [comment]
Does this really need a separate file, surely it could just go in the UI header file

**Comment by JohnnyCrazy** [comment]
Yes, aggree with @zorg93

**Comment by Frede1012** [comment]
Gimme a sec i will change it then :P

**Comment by Frede1012** [comment]
@JohnnyCrazy @zorg93 Fixed :)

**Comment by Frede1012** [comment]
Any problems @JohnnyCrazy ?

**Comment by JohnnyCrazy** [comment]
Relax, got some other stuff to do than hanging around in github :P

I'm fine with it, but want to hear @crosire thoughts first

**Comment by nevadascout** [comment]
Personally, I don't like this. I would rather it went into it's own file as we might want to use the fonts for something other than just the menu in the future.

**Comment by Frede1012** [comment]
@JohnnyCrazy Haha, sorry for bugging you man :-)
@nevadascout It's currently in the UI.hpp, i dont think we are going to use fonts for anything not UI related?

**Comment by nevadascout** [comment]
@Frede1012 My bad, I misread zorg's comment :)

**Comment by zorg93** [comment]
@nevadascout Most enums are stored in files related to them, the only exceptions are long enum hash lists that have their own file

**Comment by nevadascout** [comment]
Fair enough. I would argue that anything class level should be in it's own file, but I'm not going to lose any sleep over it :)

**Comment by kagikn** [comment]
@Frede1012 Arial isn't used for subtitles and so on, but Chalet London 1960 instead.  fontmap.xml showed the font names which is used in GTAV.

**Pull request merged**
