### PR TITLE
Added back calling Natives with IHandleable types

### PR DESCRIPTION
**Pull request by zorg93**
Added UI Changes

todo fix returning from native with IHandleable types

### CODE REVIEW

**Comment by crosire** [comment]
Sounds reasonable. But something went wrong with intendation, there's a few spaces instead of tabs in some places.

**Comment by zorg93** [comment]
thought this one was long over due but casting enums(only ones based off int/uint/int64/uint64) is no longer necessary for calling natives.This means code like this
`Function.Call<bool>(Hash.IS_THIS_MODEL_A_CAR, VehicleHash.Adder);`
will compile and run as expected

**Comment by Fireboyd78** [comment]
What's up with the scripting stuff being C# files?

**Comment by crosire** [comment]
@Fireboyd78 See #489

**Comment by Fireboyd78** [comment]
Ohhh, that's what the "experimental" branch was about. My bad, lol.

**Pull request merged**
