### PR TITLE
Used Notification.Show

### PR DESCRIPTION
**Pull request by zorg93**
Open to debate as to how to introduce this feature

### CODE REVIEW

**Comment by Frede1012** [comment]
I still think having UI.Notify is the best solution, will this really cause so many problems?

**Comment by zorg93** [comment]
Yes, when a script is a compiled dll, if void UI.Notify is what the dll was compiled with, changing it to return something will throw an error.

**Comment by Frede1012** [comment]
But aren't things like that bound to happen when the scripthook is being constantly updated?

**Comment by zorg93** [comment]
Generally not, as we try and prevent breaking existing methods where possible

**Comment by JohnnyCrazy** [comment]
I think we can do minor changes before 1.0 . After that release, we should really avoid such breaking updates and wait till the next minor (2.0) release.

**Comment by Frede1012** [comment]
^ That is exactly what I was thinking, the current state of the project should allow for such changes :-)

**Comment by nevadascout** [comment]
If we're doing this, then we need release notes for each release that detail what is being removed/added

**Comment by crosire** [comment]
@nevadascout We already have that in the releases one can download from gta5-mods.com etc. Just needs to be added to the Github releases page too.

**Comment by zorg93** [comment]
I have changed it to UI.Notify again, lose support for scripts compiled using previous version of the hook

**Comment by Frede1012** [comment]
Seems good!

**Comment by JohnnyCrazy** [comment]
I would say we merge this once 1.0 is ready. So currently existing scripts don't break and once 1.0 is released, we make a big announcement so everyone knows they have to update their mods.

@crosire

**Comment by crosire** [comment]
I think we should refactor the whole scripting API before 1.0 anyway. Clean up code a bit etc.

**Pull request merged**
