### PR TITLE
Use CLR hosting to run managed code

### LINKED ISSUE #547: ScriptHookVDotNet crashes/stops loading when ScriptHookV reloads
Not sure if this is ScriptHookVDotNet specific or more ScriptHookV's domain, but as ScriptHookV doesn't crash immediately, I'd say it belongs here. Do correct me if I'm wrong.

When having ScriptHookV.dev in the root folder and toggling it with CTRL-R, all mods register and unregister correctly except ScriptHookVDotNet, which will not unregister after one or two full reloads. It will stop working and it won't restart on subsequent ScriptHookV loads.

When exiting the game, ScriptHookV tries to unregister it (or, something) and throws an error, with GTA V crashing and showing the safe mode prompt.

[ScriptHookV.log](http://pastebin.com/Su07Qqzx)
[ScriptHookVDotNet.log](http://pastebin.com/NVAnmwxS)

Everything in `case DLL_PROCESS_DETACH:` seems to be standard ScriptHookV though. Maybe `sScriptFib` is wrong?

### PR DESCRIPTION
**Pull request by Sardelka9515**
As preparation for #1036. Fixes #547, maybe #1063 as well (not sure as I can't reproduce).

This makes the c# code previously linked to C++/CLI a standalone managed assembly and get's called during startup.

There're still some issues regarding versioning.
~~The managed initialization assembly version is set to 1.0.0.0, which makes the in-game console output the wrong version (can be fixed by fetching the latest api assembly version).~~ C++ core doesn't have any version set yet.

### CODE REVIEW

**Comment by Sardelka9515** [comment]
Looks like SDK style project require a nuget restore before build

**Comment by Sardelka9515** [comment]
I noticed some scripts will time out if the memory scanning in `NativeMemory` static constructor takes too long, not sure if it's intoduced by this or already present in previous versions. So I made sure the constuctor is called during domain setup.

Also added pattern/offset caching, which saves the scanning time after a reload and make #1162  easier to implement

**Comment by crosire** [comment]
I'm sorry, but this is too much. I'd rather not have to introduce yet another DLL in the project to make things work. But I'm willing to modify the SHVDN core in a way that would make it possible to just rename it to a DLL and have another project act as its loader. With 60c02dfed4a92c99fc3315f37999d83dd26419e6, it now can be loaded via `Assembly.Load` or any other means without locking up. So there can be a separate ASI that hosts the CLR and then loads SHVDN afterwards. This could be further extended to also make it possible to disable the SHVDN core from registering with SHV.

Good point with `NativeMemory` constructor being able to time out scripts, this already present right now and fixed this with a slightly cleaner method now: 5f514ef35b870e00e65cb0f9e3d36a9c9aaf2cdb

**Comment by kagikn** [comment]
I thought another DLL was being introduced because Sardelka9515 said he couldn't get `DllMain` in a DLL built of C++/CLI loaded [as this message says](https://github.com/crosire/scripthookvdotnet/issues/1036#issuecomment-1449177452), but maybe that failed because the DLL coundn't find `ijwhost.dll`, I guess.

**Comment by kagikn** [comment]
> I noticed some scripts will time out if the memory scanning in `NativeMemory` static constructor takes too long, not sure if it's intoduced by this or already present in previous versions. So I made sure the constuctor is called during domain setup.

I'm sure any commit older than 5f514ef had the issue where some script may time out if the static ctor of `NativeMemory` takes more than 5 seconds, and that would happen when no scripts accessed any methods/properties that internally touches `NativeMemory` and some tick event in some script accessed one of them.

**Comment by crosire** [comment]
That's fine, as per https://github.com/crosire/scripthookvdotnet/issues/1036#issuecomment-1449418370, just that the described C++ core should not live in this repository and SHVDN and SHVDNC would remain separate repositories. SHVDN would be modified so that it *can* support being loaded by aforementioned C++ core that hosts the CLR, but it also can technically still run on its own.

**Comment by Sardelka9515** [comment]
Fair enough

**Comment by kagikn** [comment]
Is #1036 worth opening? I'm asking because another DLL is probably needed to load scripts built against .NET Core/.NET 5+ since you can't use AppDomain and this PR got closed. If we never intend to add APIs built against .NET 7+, #1036 might as well deserve closed.

**Comment by crosire** [comment]
Right, my understanding is that .NET 7+ support looks very different from the current SHVDN implementation, making it essentially an entirely new project (since very little of the SHVDN core could be used with it, missing AppDomains etc.). So may as well embrace that and maintain it as such.
I'd rather not be the profile where such a big new undertaking is hosted and refined, considering that I'm not actively involved with GTA modding anymore. So #1036 is unlikely to happen in the context of SHVDN and can probably be closed, in favor of doing it via e.g. https://github.com/Sardelka9515/scripthookvdotnetcore. It might be worth the effort to make the interface between the SHVDN core and scripting APIs simple enough at least to also work with .NET Core, so that the scripting API code can be fully shared (imported via submodule + an external csproj that builds it for .NET Core instead of using the csproj in SHVDN that builds it for the .NET Framework).

**Pull request closed without merging**
