### PR TITLE
Shadowcopying assemblies to prevent file locking + Extended logging methods for scripts

### PR DESCRIPTION
**Pull request by Frede1012**

### CODE REVIEW

**Comment by crosire** [comment]
Didn't merge the logging yet. I think that should be best implemented differently (similar to ScriptSettings).

**Comment by Frede1012** [comment]
@crosire How do you mean?

**Comment by Frede1012** [comment]
@crosire I have been working a bit more on the logging system (i started adding a console). However i am unsure as to how you want it to be structured, since you rejected my logging commits. Could you take a look here: https://github.com/Frede1012/scripthookvdotnet/commit/9bd51e1445be135a83ec66ca576c3e9c78179573

I am unsure of how to implement my console class (my current implementation seems to be crashing OnDraw(), however i dont know how to view a stacktrace), and the structure of the logging system. Maybe you could push some changes to help?

**Comment by crosire** [comment]
I prefer to work after the KISS principle, meaning to keep Script Hook small without unnecessary things.

Take a look at the "ScriptSettings" class for instance, it's really basic, but sufficient for the common case and if somebody needs more functionality (like writing configuration to a file instead of only reading) he can simply write his own implementation and use that one instead. The same should apply for logging. Instead of an overloaded class provide some very simple interface which does what it's supposed to do: Logging should do exactly that, log some message (preferrably with a timestamp) to some output stream. Not more, not less.

About the Console: It's a good idea to keep it in Main and not put it into ScriptDomain (which I probably would have done before realizing that's not a good idea), because that allows us to have multiple ScriptDomains in the future (if we ever decide to do so), but still the one main console.

**Comment by Frede1012** [comment]
@crosire I see, so how would you propose that the logging class look like? Also, any advice on the console crashing on Draw(), is there any way to get a stacktrace?

**Comment by Frede1012** [comment]
@crosire There seems to be a problem with using the Native Functions from Main, are you aware of this? This is whats causing my errors. The crash happens when the native function is called, however if the console is drawn in the script class, no problems are to be found.

**Comment by crosire** [comment]
Yes, native functions can only be called from inside an active ScriptDomain. This was a design choice.

**Pull request closed without merging**
