### PR TITLE
Added Entity::HasCollision, Entity::MaxSpeed, Entity::SetProofs

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by zorg93** [comment]
about the Entity Proofs thing, I'm thinking of making a different system where you can get and set each individual proof

**Comment by crosire** [comment]
I'd do it via simple "IsBulletProof" etc. properties. We can additionally store those values as fields in the entity class, so they are updated correctly when set (since you have to set all of them in one go apparently).

**Comment by zorg93** [comment]
or you could just read and write the bit directly from memory...

**Comment by zorg93** [comment]
something like this would work for bulletproof
bool Entity::BulletProof::get()
{
	UINT64 Address = MemoryAccess::GetAddressOfEntity(this->Handle);
	return Address != 0 ? bitTest((int*)(Address + 392), 5) : false;
}

**Comment by zorg93** [comment]
Getting and setting individual proofs have been implemented and tested in #313

**Pull request merged**
