### PR TITLE
Added Date-class

### LINKED ISSUE #109: World.CurrentDate does not return
I tried to receive the current day of the week but this little spike demonstrates World.CurrentDate does not return because the spike can't make it to UI.ShowSubtitle anymore.

using System.Windows.Forms;
using Cyron43.GtaV.Common;
using GTA;

namespace GTAVSpikes
{
   /// <summary>
   /// Do whatever you currently need to research here.
   /// </summary>
   public class DynamicSpike : Script
   {
      public DynamicSpike()
      {
         KeyDown += OnKeyDown;
         UI.Notify("Spike is running.");
      }

      private void OnKeyDown(object sender, KeyEventArgs e)
      {
         var testKey = new KeyContainer
                       {
                          Alt = false,
                          Ctrl = false,
                          Key = Keys.Space,
                          Name = "Test",
                          Shift = false
                       };
         if(KeyHandlingCommons.KeyIs(testKey, e))
            DoTest();
      }

      private void DoTest()
      {
         UI.Notify("DoTest called.");
         var weekDay = World.CurrentDate.DayOfWeek;
         UI.ShowSubtitle("Today is " /* + weekDay*/); //Shows only when the line before is commented out.
      }
   }
}

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
This fixes #109 
It's also a minimalistic implementation, so no big helper methods.

Quickly created this, if you find any mistakes, just shout it out.

### CODE REVIEW

**Comment by crosire** [comment]
I would rather make this a value class ...

**Comment by zorg93** [comment]
If you're going to include dates and times, Surely it makes more sense to call the class DateTime

**Comment by JohnnyCrazy** [comment]
Done @crosire 

Renamed it to `GTADateTime` so there are no conflicts with the normal DateTime (Which is also used a lot in scripts)

**Comment by SeijiSuenaga** [comment]
Wouldn't it be better to just qualify it like GTA.DateTime?

**Comment by JohnnyCrazy** [comment]
@SeijiSuenaga
IMO we should not interfere with the names of the .NET standard names. But thats just my favorite naming-style.

**Comment by zorg93** [comment]
@JohnnyCrazy About not interfering with .NET standard names, The GTA::Menu class interferes with the System::Windows::Forms::Menu class, but that has gone un-noticed

**Comment by crosire** [comment]
Yes, I would prefer GTA.DateTime too. Namespaces are there for a reason =).

**Comment by JohnnyCrazy** [comment]
Done, sorry for the late push @crosire

**Comment by crosire** [comment]
Can't merge that yet though, since it will break existing scripts using the World::CurrentDate property. So this has to be merged close to 2.0.

**Comment by JohnnyCrazy** [comment]
How about a 2.0 branch?

**Comment by IncoCode** [comment]
How about to add some checks to properties of year (2010-2013) and month (0-11)?

**Comment by JohnnyCrazy** [comment]
IMO we should only provide proper getters and setters. We also don't check the inputs in other native functions, so why should we start here?

**Comment by IncoCode** [comment]
To avoid a bunch of questions like "i'm trying to set date in 30.12.2200 and nothing happens".
Or, at least, add information (in xml comments/wiki) about correct values.

**Comment by JohnnyCrazy** [comment]
Merged in c58176d056e6541f65c244cd609ed8e484189cb9

**Comment by JohnnyCrazy** [comment]
@crosire Anything missing since it's in a feature branch?

**Comment by crosire** [comment]
While the dev branch is for development, it could very well be that we want to release some 1.1 before 2.0, which wouldn't be possible when I merge this now.

**Pull request closed without merging**
