### PR TITLE
Added new Vehicle hashes and Weapon components from 757 update

### PR DESCRIPTION
**Pull request by zorg93**

### CODE REVIEW

**Comment by crosire** [comment]
Btw. There is no good reason in having `VehicleHash`, `PedHash` and `WeaponHash` in the `Native` namespace when most other enums aren't. We should move them out of there.

**Comment by zorg93** [comment]
@crosire I just moved the hash enums into the GTA Namespace, makes more sense in there

**Comment by UnknownModder** [comment]
@Fireboyd78 @zorg93 

Also Xls and Xls2 should be XLS and XLS2. Aaaaaannnnnddddd, the car's name is BestiaGT**S** not BestiaGT.

**Comment by zorg93** [comment]
I realised about BestiaGT a couple of hours ago when I searched through the decompiled scripts for its hash and couldnt find it.(for some reason a few seconds after spawning the cars on 757 they get deleted) That issue should go soon though(hopefully) if not we found a work around

**Comment by zorg93** [comment]
Fixed in #501

**Pull request merged**
