### PR TITLE
Added Global getter/setters

### PR DESCRIPTION
**Pull request by zorg93**
Reworked worldGetAll/Nearby Methods
Added back World.GetNearbyPeds(Ped, radius);
Added Helper class
Tweaks to Raycast
Added GetCrosshairCoordinates

### CODE REVIEW

**Comment by zorg93** [comment]
#259 #252 Fixed in this commit
Also changed added 1 to max length parameter when showing keyboard to account for the string terminator character('\0')

**Comment by zorg93** [comment]
#283 Fixed in this commit by incrimenting the max length on the actual native call instead of functions that call it
#223 Added Global access

**Comment by Nacorpio** [comment]
I only get the player when trying to use GetAllEntities().

**Comment by zorg93** [comment]
When i tested they all worked perfectly

**Comment by zorg93** [comment]
GetAllEntites Works fine for me - http://puu.sh/jQhEt/b3e14c6de3.png
What game version are you running

**Comment by Nacorpio** [comment]
The latest one.

**Comment by zorg93** [comment]
steam or warehouse

**Comment by Nacorpio** [comment]
Steam.

**Comment by zorg93** [comment]
Hmm Looks like Im gonna need a 1.0.393.4 steam exe to check this out. it seemed to work fine on older steam game versions. Can you show me the code you are using

**Comment by Nacorpio** [comment]
I am just simply setting the value to a List<Entity> by using Linq, and then I'm retrieving them by using a menu API.

**Comment by Nacorpio** [comment]
There's certainly nothing wrong with my code.

**Comment by zorg93** [comment]
make sure you are using this build of the hook - https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/Build%20No.%20432/artifacts
Put this in a cs file in your scripts folder and start gta, if you see loads of yellow flashing markers, the problems your code. If you dont then the issue is the steam exe failing a signature somewhere

**Comment by Nacorpio** [comment]
I can only see the player, still.

**Comment by zorg93** [comment]
Huh the signatures are all correct, I have no idea why it isnt working for you

**Comment by Nacorpio** [comment]
Apparently, when I come close to vehicles, they also get marked, but that's it.

**Comment by zorg93** [comment]
The script only marks entities within 20m of you
looks kind of like this, the things in the garage are about as far as it will draw the markers
gta5_2015_08_27_16_52_16_374

**Comment by Nacorpio** [comment]
It doesn't draw props or peds on my side, though.

**Comment by zorg93** [comment]
are you using ragepluginhook, someone just tested on the steam version and got this result
http://puu.sh/jQxcw.jpg

**Comment by Nacorpio** [comment]
No, I'm not.

**Comment by Nacorpio** [comment]
Apparently, the peds get marked when I punch them.
What the hell is going on?

**Comment by zorg93** [comment]
Are you updated to the latest version of scrupthookv other than that i cant think of any issues

**Comment by Nacorpio** [comment]
Let me check.

**Comment by zorg93** [comment]
@Nacorpio any idea what was causing the issue

**Comment by Nacorpio** [comment]
Still the same issue.

**Comment by JohnnyCrazy** [comment]
Working fine here too, latest steam version.
alt

@Nacorpio Did you double-check everything? :P

**Pull request merged**
