### PR TITLE
Execute scripts in the main thread

### PR DESCRIPTION
**Pull request by kagikn**
We should test if most scripts work with this change, but this PR will make users and script developers happy if there aren't serious issues!
I just made minimum changes to make scripts execute in the main thread, so we should tidying up code that is (was) related to script threads later.
If this PR is merged, we should be able to add `World.GetAll*IEnumerable` and `World.GetNearby*IEnumerable` variants without being worried about performance issues, too.

### CODE REVIEW

**Comment by kagikn** [comment]
I forgot this makes `Script.Wait` not pause scripts immediately. Need to find a solution.

**Comment by kagikn** [comment]
This will be much more challenging than I thought. Let me fix #966 first because that will be easier to fix than this.

**Comment by kagikn** [comment]
Another thing that should be considered. [Threads own their CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-5.0), so I have to keep compatibility about this.
I should fix scripting stuff that are not working in later game versions first, though. Or, add useful features, especially ones that must be executed in the main thread.

**Comment by kagikn** [comment]
I didn't realize GitHub has Draft Pull Request💀 Now everyone can easily recognize this is still in progress.

**Comment by crosire** [comment]
This is superseded by 035d9918d5ee295344e8c9f4200d56300679207d which does this, but makes it opt-in (through a script attribute) to ensure existing ones behave the same as before.

**Comment by kagikn** [comment]
I appreciate 035d991 and 3798c94, I can see the difference in performance wise! I wouldn't say I need some protection against the script locking up the game process by accident when `NoScriptThread` is set, but I hope we will be able to use `Script.Wait()` and `Script.Yield()` when it's set (you might carelessly call one of those indirectly via some methods such as `World.Create*` if model is not loaded).

**Comment by crosire** [comment]
Unfortunately no, `Wait`/`Yield` will throw an exception when called in a script with `NoScriptThread`. They aren't really possible to implement in the current ScriptDomain design without locking everything up I think (since we can't jump out of the `Wait` call and easily do something else in the meantime). When scripts run in separate threads it's no issue, can just pause the thread, but with scripts in the main thread that doesn't work.

**Pull request closed without merging**
