### PR TITLE
Add support for editing weapon components

### PR DESCRIPTION
**Pull request by zorg93**

### CODE REVIEW

**Comment by Fireboyd78** [comment]
Nice work! Do you have an example of what the data looks like in memory? The whole `long long *` thing is kinda scary and could probably be turned into a struct that's easier to understand. It would also allow you to create a helper function to get the weapon component data, cutting down on the amount of copy/paste code.

**Comment by Fireboyd78** [comment]
What do you think about this?

`public enum class WeaponComponent : System::UInt32
{
	AdvancedRifleClip01 = 0xFA8FA10F,
	AdvancedRifleClip02 = 0x8EC1C979,
	AdvancedRifleVarmodLuxe = 0x377CD377,
	ApPistolClip01 = 0x31C4B22A,
	ApPistolClip02 = 0x249A17D5,
	ApPistolVarmodLuxe = 0x9B76C72C,
	AssaultRifleClip01 = 0xBE5EEA16,
	AssaultRifleClip02 = 0xB1214F9B,
	AssaultRifleVarmodLuxe = 0x4EAD7533,
	AssaultSMGClip01 = 0x8D1307B0,
	AssaultSMGClip02 = 0xBB46E417,
	AssaultSMGVarmodLowrider = 0x278C78AF,
	AssaultShotgunClip01 = 0x94E81BC7,
	AssaultShotgunClip02 = 0x86BD7F72,
	AtArAfGrip = 0xC164F53,
	AtArFlsh = 0x7BC4CDDC,
	AtArSupp = 0x837445AA,
	AtArSupp02 = 0xA73D4664,
	AtPiFlsh = 0x359B7AAE,
	AtPiSupp = 0xC304849A,
	AtPiSupp02 = 0x65EA7EBB,
	AtRailCover01 = 0x75414F30,
	AtScopeLarge = 0xD2443DDC,
	AtScopeLargeFixedZoom = 0x1C221B1A,
	AtScopeMacro = 0x9D2FBF29,
	AtScopeMacro02 = 0x3CC6BA57,
	AtScopeMax = 0xBC54DA77,
	AtScopeMedium = 0xA0D89C42,
	AtScopeSmall = 0xAA2C45B4,
	AtScopeSmall02 = 0x3C00AFED,
	AtSrSupp = 0xE608B35E,
	BullpupRifleClip01 = 0xC5A12F80,
	BullpupRifleClip02 = 0xB3688B0F,
	BullpupRifleVarmodLow = 0xA857BC78,
	BullpupShotgunClip01 = 0xC94E550E,
	CarbineRifleClip01 = 0x9FBE33EC,
	CarbineRifleClip02 = 0x91109691,
	CarbineRifleVarmodLuxe = 0xD89B9658,
	CombatMGClip01 = 0xE1FFB34A,
	CombatMGClip02 = 0xD6C59CD6,
	CombatMGVarmodLowrider = 0x92FECCDD,
	CombatPDWClip01 = 0x4317F19E,
	CombatPDWClip02 = 0x334A5203,
	CombatPistolClip01 = 0x721B079,
	CombatPistolClip02 = 0xD67B4F2D,
	CombatPistolVarmodLowrider = 0xC6654D72,
	CompactRifleClip01 = 0x513F0A63,
	CompactRifleClip02 = 0x59FF9BF8,
	DBShotgunClip01 = 0x29EA741E,
	FireworkClip01 = 0xE4E4C28D,
	FlareGunClip01 = 0x93E9BD99,
	FlashlightLight = 0xDDB7390F,
	GrenadeLauncherClip01 = 0x11AE5C97,
	GusenbergClip01 = 0x1CE5A6A5,
	GusenbergClip02 = 0xEAC8C270,
	HeavyPistolClip01 = 0xD4A969A,
	HeavyPistolClip02 = 0x64F9C62B,
	HeavyPistolVarmodLuxe = 0x7A6A7B7B,
	HeavyShotgunClip01 = 0x324F2D5F,
	HeavyShotgunClip02 = 0x971CF6FD,
	HeavySniperClip01 = 0x476F52F4,
	HomingLauncherClip01 = 0xF8132D3F,
	KnuckleVarmodBallas = 0xEED9FD63,
	KnuckleVarmodBase = 0xF3462F33,
	KnuckleVarmodDiamond = 0x9761D9DC,
	KnuckleVarmodDollar = 0x50910C31,
	KnuckleVarmodHate = 0x7DECFE30,
	KnuckleVarmodKing = 0xE28BABEF,
	KnuckleVarmodLove = 0x3F4E8AA6,
	KnuckleVarmodPimp = 0xC613F685,
	KnuckleVarmodPlayer = 0x8B808BB,
	KnuckleVarmodVagos = 0x7AF3F785,
	MGClip01 = 0xF434EF84,
	MGClip02 = 0x82158B47,
	MGVarmodLowrider = 0xD6DABABE,
	MachinePistolClip01 = 0x476E85FF,
	MachinePistolClip02 = 0xB92C6979,
	MarksmanPistolClip01 = 0xCB9E41ED,
	MarksmanRifleClip01 = 0xD83B4141,
	MarksmanRifleClip02 = 0xCCFD2AC5,
	MicroSMGClip01 = 0xCB48AEF0,
	MicroSMGClip02 = 0x10E6BA2B,
	MicroSMGVarmodLuxe = 0x487AAE09,
	MinigunClip01 = 0xC8DE6F06,
	MusketClip01 = 0x4ED2073F,
	Pistol50Clip01 = 0x2297BE19,
	Pistol50Clip02 = 0xD9D3AC92,
	Pistol50VarmodLuxe = 0x77B8AB2F,
	PistolClip01 = 0xFED0FD71,
	PistolClip02 = 0xED265A1C,
	PistolVarmodLuxe = 0xD7391086,
	PoliceTorchFlashlight = 0xC5A30FED,
	PumpShotgunClip01 = 0xD16F1438,
	PumpShotgunVarmodLowrider = 0xA2D79DDB,
	RPGClip01 = 0x4EA573B3,
	RailgunClip01 = 0x384F3E8,
	RevolverClip01 = 0xE9867CE3,
	RevolverVarmodBoss = 0x16EE3040,
	RevolverVarmodGoon = 0x9493B80D,
	SMGClip01 = 0x26574997,
	SMGClip02 = 0x350966FB,
	SMGVarmodLuxe = 0x27872C90,
	SNSPistolClip01 = 0xF8802ED9,
	SNSPistolClip02 = 0x7B0033B3,
	SNSPistolVarmodLowrider = 0x8033ECAF,
	SawnoffShotgunClip01 = 0xC7D62225,
	SawnoffShotgunVarmodLuxe = 0x85A64DF9,
	SniperRifleClip01 = 0x9BC64089,
	SniperRifleVarmodLuxe = 0x4032B5E7,
	SpecialCarbineClip01 = 0xC6C7E581,
	SpecialCarbineClip02 = 0x7C8BD10E,
	SpecialCarbineVarmodLowrider = 0x730154F2,
	SwitchbladeVarmodBase = 0x9137A500,
	SwitchbladeVarmodVar1 = 0x5B3E7DB6,
	SwitchbladeVarmodVar2 = 0xE7939662,
	VintagePistolClip01 = 0x45A3B6BB,
	VintagePistolClip02 = 0x33BA12E8,
    
    Invalid = 0xFFFFFFFF,
};`

**Comment by zorg93** [comment]
The Enum was generated using this http://pastebin.com/txr9eWhh. The names used come from dumping weaopn files from rpfs. the long functions were also generated in a similar way. that explains why some things look a little weird. Varmod components are the luxury finishes on weapons

**Comment by zorg93** [comment]
the function for getting components was generated from this
http://pastebin.com/7crB0j7X
As for the long long *, there isnt a full documentation of dlc_weapon_data and dlc_weapon_component_data. so just using a native array is a quick and easy solution

**Comment by zorg93** [comment]
Although I've changed the enum names. Its not really that important, I've set it up so you can access a weapons components by index, and you can get the actual component names(for displaying in any kind of trainer) from the gxt files so the script developer should never need to directly use the component enum name

**Comment by Fireboyd78** [comment]
Thanks for explaining that! Real quick question if you don't mind -- how would I go about reverse engineering natives? It seems that the executable is encrypted, and the native hashes change with every update.

**Comment by zorg93** [comment]
Not that this has anything to do with the PR but anyway. The executable gets unpacked when you launch it, so you can dump it from memory and it will be in a workable state, however since R* started trying to hide native initialization dumping that is slightly harder. Basically they leave the native tables encrypted and only decrpyt them when they are being used, then they get encrypted again. So in order to extract native tables you would have to attach a debugger and dump when tables get decrypted. Anyway thats too complicated for me so i just use an old game exe(335 i believe) and work with natives using that one. Then I can sig scan parts of the native to find its relevant code in later game versions

**Comment by kagikn** [comment]
Probably, we should rename ```WeaponComponent``` to ```WeaponComponentHash``` for the future.

**Comment by zorg93** [comment]
I thought about WeaoponComponentHash but decided against it as the Hash is generally used with Models in here (and native ofc)

**Comment by crosire** [comment]
Good choice, since I'm considering to rename the ```PedHash``` etc. enums and to move them out of the ```Native``` namespace for 3.0.

**Comment by kagikn** [comment]
Just as we can't create ```VehicleDoor``` and ```VehicleWindow``` class, I'm afraid of a name conflict.

**Comment by zorg93** [comment]
You can create them in a different namespace, but why do you need to create a VehicleDoor, VehicleWindow or WeaponComponent class

**Comment by kagikn** [comment]
I believe too big classes are evil, and I believe vehicles have a pointer of doors and windows. I confirmed they have individual wheel pointers.[```CVehicle + 0xAA0```]

**Comment by zorg93** [comment]
You didnt answer the question though

**Comment by kagikn** [comment]
I think we need their classes to separete the roles.  For example, vehicle entities have individual door objects, don't they?

**Comment by Fireboyd78** [comment]
I agree with @kagikn. We need to prevent any future name conflicts. Maybe we could prefix all enum with an "E", like for example `EVehicleDoor`. This isn't a very common naming convention for C# code, but since the script hook (and GTA 5) are written in C++, it would make sense to follow typical naming conventions.

**Comment by Fireboyd78** [comment]
My bad, I forgot to mention that the enum naming convention is very popular among C++ game designers.

**Comment by crosire** [comment]
Yuk. It may be popular among Unreal projects, but that's about it, in my experience. This whole prefixing thing is a relic from older times when there were no good IDEs around (similar to Hungarian notation).

**Pull request merged**
