### PR TITLE
Added Prop Hashes, corresponding Model Code and World::CreateObject

### PR DESCRIPTION
**Pull request by Tatros**
The Prop Hashes are from http://ecb2.biz/releases/GTAV/lists/objects.txt
I don't know how accurate they are, but I spawned a few objects with
World::CreateObject and couldn't notice any irregularities.

Please note: IntelliSense doesn't always handle the large enum very well
and may slow down the build process. Any idea on how to fix this?

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Do we really need this large enum? Maybe just provide a string Parameter?

**Comment by Tatros** [comment]
I'm not happy with the enum either, mainly because it slows down the build. Question is, how else are you going to map the Strings their corresponding Hashes?

**Comment by JohnnyCrazy** [comment]
Mm... The only thing i could imagine is some kind of binary file which gets read at start, but idk

**Comment by screeny05** [comment]
May i suggest the naive approach of parsing the file? do it at runtime and
convert the list into a map, which then is accessible via a string index.
Am 12.05.2015 01:19 schrieb "Tatros" <notifications@github.com>:

**Comment by crosire** [comment]
Doesn't GET_HASH_KEY work just fine for those too?

**Comment by Tatros** [comment]
Good point. It does. You're still not going to know what String to put in there, unless you have the list. But I guess it doesn't need to be in there as an enum, so I removed that for now.

**Comment by Nacorpio** [comment]
Just define two arrays and use the index. It is almost like a map.

**Pull request merged**
