### PR TITLE
Added some Native Hashes.

### PR DESCRIPTION
**Pull request by Tanjitsu**
Native Hashes - 
_GET_VEHICLE_MAX_SPEED
_IS_PLAYER_VEHICLE_RADIO_ENABLED
DOES_NAVMESH_BLOCKING_OBJECT_EXIST
_SET_CUSTOM_RESPAWN_POSITION
_SET_NEXT_RESPAWN_TO_CUSTOM

### CODE REVIEW

**Comment by crosire** [comment]
There is a `Run NativeGen` target in the Visual Studio solution that updates the enum with data retrieved from http://dev-c.com/nativedb/ on its own.

**Comment by Tanjitsu** [comment]
> There is a Run NativeGen target in the Visual Studio solution that updates the enum with data retrieved from http://dev-c.com/nativedb/ on its own.

Oh nice ! I just added ones i wanted but couldn't find in the Native hash list.

**Comment by zorg93** [comment]
@crosire the issue is nativedb is poorly maintained and doesn't add natives included in newer patches

**Comment by kagikn** [comment]
Yeah, that's true. We

**Pull request closed without merging**
