### PR TITLE
Improved Menu API

### PR DESCRIPTION
**Pull request by StijnBrouwer**
I made some improvements to the Menu API and a better example script.

### CODE REVIEW

**Comment by StijnBrouwer** [comment]
Oh, didn't notice it isn't mergable.

**Comment by IncoCode** [comment]
Make pull from git@github.com:crosire/scripthookvdotnet.git . Then resolve conflicts and make commit.

**Comment by StijnBrouwer** [comment]
I hope I did that right...

**Comment by StijnBrouwer** [comment]
It didn't give any merge conflicts, so I think I fucked it up.

**Comment by StijnBrouwer** [comment]
The code looks like it merged correctly?!

**Comment by StijnBrouwer** [comment]
I think I still need to clean my code up though

**Comment by StijnBrouwer** [comment]
Yeah, I need to change those types first

**Comment by StijnBrouwer** [comment]
I fixed it, I will test it real quick before committing though.

**Comment by StijnBrouwer** [comment]
Shit, I lost one commit

**Comment by IncoCode** [comment]
You can restore it: git reflog. Then cherry pick or merge.

**Comment by StijnBrouwer** [comment]
No need, I already fixed it, it was just one file.

**Comment by StijnBrouwer** [comment]
Done

**Comment by Monsterxsync** [comment]
@StijnBrouwer How do we use the ListMenu?

**Pull request merged**
