### PR TITLE
MenuItem Improvements

### PR DESCRIPTION
**Pull request by Frede1012**
Added value properties and constructor with value variable to MenuItems: Toggle, Enum & Numeric.

MenuLabel & Button automatically updates text when set a new caption.

### CODE REVIEW

**Comment by nmdanny** [comment]
By the way, in MenuNumericScroller, nothing invokes mChangeAction (it's been like that before your change too) whereas it should be invoked in Change.

**Comment by Frede1012** [comment]
@nmdanny Fixed ^
Are you merging this? @crosire or @JohnnyCrazy

**Comment by JohnnyCrazy** [comment]
Seems good to me :+1:

**Comment by JohnnyCrazy** [comment]
@Frede1012 BTW, any reason why the `UpdateText` method is now private?

**Comment by Frede1012** [comment]
@JohnnyCrazy The Caption can't be changed without updating the text anyway, so it seemed unnecessary to have it public.

**Comment by JohnnyCrazy** [comment]
@Frede1012 Yea makes sense.

**Comment by Frede1012** [comment]
@JohnnyCrazy No problem :)

**Comment by frodzet** [comment]
Thanks for the response :-)

**Pull request merged**
