### PR TITLE
Blip upd

### PR DESCRIPTION
**Pull request by IncoCode**
Added:
* Blip::Sprite (getter, setter)
* Blip::ShowNumber and Blip::HideNumber
* Blip::Type (getter)
* Entity::CurrentBlip
* World::ActiveBlips

Example:
```c#
// type 4 - player's marker
Blip blip = World.ActiveBlips.FirstOrDefault( b => b.Type == 4 );
if ( blip != null )
{
	player.Position = blip.Position;
	UI.ShowSubtitle( "Done", 2000 );
}
else
{
	UI.ShowSubtitle( "Not found", 2000 );
}
```

### CODE REVIEW

**Comment by crosire** [comment]
Whoops, too fast. Yeah @JohnnyCrazy has a point there.

**Comment by IncoCode** [comment]
@JohnnyCrazy , i don't know, any examples of "specific for-loop".

**Comment by JohnnyCrazy** [comment]
A newbie to GTA Scriting would maybe do the following:
````c#
for(int i = 0; i < World.ActiveBlips.length; i++)
{
    Blip p = World.ActiveBlips[i];
    //A lot of unnecessary calls
}
````

Getters should just not contain that much code + arrays in getters is tricky

**Comment by IncoCode** [comment]
@JohnnyCrazy , well, agree. Then same problem can be with World::GetNearbyPeds() etc...

**Comment by IncoCode** [comment]
Hopefully, if we remove a property ActiveBlips and add a GetActiveBlips method, it will prevent the writing of such code like above one.

**Comment by JohnnyCrazy** [comment]
@IncoCode 
Yea that is my hope. A Method `GetActiveBlips` would clearly say "If you call me again, I might change my values". arrays in getters is tricky :smile:

**Pull request merged**
