### PR TITLE
Add AnimationDictionary & AnimationSet

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by crosire** [comment]
I'm not convinced that the two new classes are useful. The other additions are nice though.

**Comment by kagikn** [comment]
We have to load an animation dictionary/set before using a function which use them as a parameter, or the function doesn't work properly. I think those classes are also useful to suggest that animation dictionaries/sets are needed to load.

**Comment by zorg93** [comment]
Instead of creating a class to remind people. why not just put the code in the method for changing animationset that checks if the set is loaded, if not load it, then apply the animation

**Comment by crosire** [comment]
Agreed. It would be simpler to automatically load them behind the scenes. We do that for models in ```World.CreatePed``` too.

**Comment by kagikn** [comment]
Another reason is clarify the behavior.
```PlayAnimation(AnimationDictionary animDict, string animName, float blendInSpeed, int duration, AnimationFlags flags)
PlayAnimation(string animDict, string animName, float blendInSpeed, int duration, AnimationFlags flags)```
I think the first one is easier to make a mistake than the second one.

**Comment by kagikn** [comment]
So, are you convinced of the necessity of ```AnimationDictionary``` and ```AnimationSet```?

**Comment by kagikn** [comment]
@crosire I really wonder why you don't mention this PR after my long explanations.

**Comment by crosire** [comment]
Sorry, I saw the notifaction on my mobile, but forgot about it then.
I'm still not convinced. The only use I see in these classes is to explicitly load and unload the assets, which is something a script programmer should not have to bother with. This is something that should happen behind the scenes. The other additions I happily merge, but ```AnimationDictionary``` and ```AnimationSet``` I don't like.

**Comment by kagikn** [comment]
Alright, I removed ```AnimationDictionary``` and ```AnimationSet```.

**Pull request merged**
