### PR TITLE
Add Dependency System

### PR DESCRIPTION
**Pull request by Dakota628**
Example usage in scripts:
```csharp
[DependsOn("MyNamespace.MyType")]
[DependsOn("MyNamespace.AnotherType")]
public class MyScript: Script {
...
}
```

Where "MyNamespace.MyType" is the rype's full name (->GetType()->FullName)

### CODE REVIEW

**Comment by Dakota628** [comment]
Noticed some things that should be tweaked/fixed I'll fix them later today.

**Comment by Dakota628** [comment]
New usage as of 90876d9
```csharp
[DependsOn("MyNamespace.MyType", "MyNamespace.AnotherType")]
public class MyScript: Script {
...
}
```

**Comment by JohnnyCrazy** [comment]
Looks very good to me :+1:
@crosire

**Comment by crosire** [comment]
I'd use a System::Type argument instead, so you can use typeof, much like in [Unity](http://docs.unity3d.com/ScriptReference/RequireComponent.html).

**Comment by zorg93** [comment]
How would type work if the object is in another assembly

**Comment by Dakota628** [comment]
@zorg93 It should work. You'll have the assembly referenced already.

**Comment by JohnnyCrazy** [comment]
Is there any case where you would depend on a library but don't need a reference?

**Comment by zorg93** [comment]
@Dakota628 @JohnnyCrazy Sorry I wasnt thinking straight

**Comment by Dakota628** [comment]
@crosire @JohnnyCrazy 8e45ba uses Types.

**Comment by crosire** [comment]
Added in 70d55737b105eab4859f349caf579f9883c81cfe. I decided to implement in slightly differently: It uses less code and should be a little faster.

**Pull request closed without merging**
