### PR TITLE
Rebase of master,

### PR DESCRIPTION
**Pull request by ricci07**
Added World.GetDistance
Added Ped.GetDistanceTo
Added Vehicle.GetDistanceTo
Added Entity.GetDistanceTo
Added Game.PlayMusic
Added Game.StopMusic

### CODE REVIEW

**Comment by ricci07** [comment]
Did you remove the veh.dist, and the rest, or did something mess up again!

If you did remove them, how come? To put them as a position member?

**Comment by crosire** [comment]
I did remove them, since the same is implemented with World.GetDistance, so those are superflous.

**Comment by ricci07** [comment]
Hmmm... I thought it would be useful as you could just use the current object as the origin position. I looked at what Tim did for IV, and he added one for each <object> with a position property.

So it would be like: 

player.character.position.getDistanceTo(myveh.position)
Myped.position.getDistanceTo(myObj.position)

**Comment by crosire** [comment]
Fair enough. But you don't need to add them to Entity, Ped and Vehicle. Just add it to Entity. Ped and Vehicle inherit from Entity and thus have that method automatically too.

**Comment by ricci07** [comment]
I knew there was a fancy way. :) I had a feeling because peds and veh are as you say; entity's.

**Pull request merged**
