### PR TITLE
Add Smuggler's Run Vehicles

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by Tanjitsu** [comment]
While this one is pending... 
Could fix ... "FireTruck" is not the model name... it is "FireTruk".

**Comment by kagikn** [comment]
Reverted "FireTruck" to "FireTruk" in the v3 branch, this branch shouldn't change "FireTruck" to "Firetruk" for compatibility, though.

**Comment by kagikn** [comment]
Ah, I forgot to add one thing, the halloween weather (string), this was added about 1 year though.

**Comment by kagikn** [comment]
Didn't noticed Rockstar added `u_m_y_smugmech_01` until I saw Simple Trainer's changelog, will add the hash.

**Pull request merged**
