### PR TITLE
Add script

### PR DESCRIPTION
**Pull request by Tanjitsu**
Updated V3 / Core ASI to have the option to add / pause / abort scripts from scripts.

This is a reworked version of my previous ScriptInstance for the new Master Branch.
This leaves the existing system the same but extends with AddScript Method available from Script.

### CODE REVIEW

**Comment by crosire** [comment]
I'm not sure I understand the purpose of `SetWait`?

**Comment by Tanjitsu** [comment]
SetWait can be called on a script instance to set a wait value for the scripts next MainLoop.

I put an example script using the new functions.
MainScript.AIone.SetWait()

Its not static, the wait does not execute on the "currentlyExecuting" thread. It is stored in the relevant instance.

**Comment by crosire** [comment]
I'd prefer if that's not part of this pull request, since it doesn't seem necessary to get script instances working in general.

**Comment by Tanjitsu** [comment]
@crosire I messaged you on Gitter.

**Pull request closed without merging**
