### PR TITLE
Added Support for getting nearby objects with a position

### PR DESCRIPTION
**Pull request by boxzmodder**

### CODE REVIEW

**Comment by Nacorpio** [comment]
You guys know we all have been waiting for this! =D

**Comment by IncoCode** [comment]
You tried to compile it?

**Comment by Frede1012** [comment]
Ehm, this isn't going to work, the native function needs to have a ped passed?

**Comment by Nacorpio** [comment]
That's true. I just checked the code, and saw that the build failed. I don't know what he's trying to do here.

**Comment by Frede1012** [comment]
This code doesn't even make sense, he is passing a variable that he doesn't have.

**Comment by Frede1012** [comment]
If we had to have a function that used a position, we had to spawn a ped, run the native function and then delete it again. However, i don't know if thats a good idea or not.

**Comment by Nacorpio** [comment]
That's what I thought he did at first.

**Comment by AsgerNohns** [comment]
Sorry guys!
Gotta go fix it! :)

**Comment by boxzmodder** [comment]
I don't know what I'm doing wrong? Any ideas?

**Comment by Frede1012** [comment]
Are you sure you know what you are doing?
Also, i meant World::CreateRandomPed(), but you should pass the position.

**Comment by boxzmodder** [comment]
I know only a bit of c++ i am more of a c# guy, but i thought i could do this, but it was harder than i thought :3

**Comment by Frede1012** [comment]
I'm in the same boat :)

**Comment by boxzmodder** [comment]
Now i ran it through Visual Studio before submitting

**Comment by Frede1012** [comment]
Looks better, you don't need to have the same function twice though, you can just pass your created ped to one of the functions that require a ped :)

**Comment by boxzmodder** [comment]
Yeah, i tried that but i don't know how i should delete the Ped then?

**Comment by crosire** [comment]
```c#
Ped ^ped = CreateRandomPed(position);
Native::Function::Call(Native::Hash::SET_ENTITY_VISIBLE, ped->Handle, 0);
array<Ped ^> ^result = GetNearbyPeds(ped, radius);
ped->Delete();
return result;
```
?

**Comment by boxzmodder** [comment]
Ahh... I tried that but i forgot the  ^ symbol xD

**Comment by Nacorpio** [comment]
What does ^ even do? I'm always confused by that symbol.

**Comment by crosire** [comment]
It's C++/CLI notation and marks the variable as being a managed GC (garbage collector) handle, in contrast to * for a normal, unmanaged pointer.

**Comment by boxzmodder** [comment]
Sorry for the spam..

**Comment by Nacorpio** [comment]
@crosire Ah, that makes sense. So the ^ is better to use than the *, I assume?

**Comment by crosire** [comment]
None of them is better. They are used for different purposes. You can't have a native pointer to an managed object, simply because the GC is allowed to rearrange memory all the time which would make the pointer point to invalid memory.

**Comment by Nacorpio** [comment]
Alright. Thank you for the detailed explanation.

**Comment by boxzmodder** [comment]
@crosire Do you merge this?

**Comment by JohnnyCrazy** [comment]
Mh...it's a pretty hacky solution, but it's a solution I guess.
Although we should change it to use memory-reading some time in the future.

**Comment by crosire** [comment]
I'm a bit unhappy about the commit history =P

**Comment by Frede1012** [comment]
Not sure if this is too "hackish" of a solution to use, maybe we should wait for a better native function? Also, i agree with @crosire on the state of the commit history :-P

**Comment by crosire** [comment]
This will be properly implemented in #191.

**Pull request closed without merging**
