### PR TITLE
New blip color, Set vehicle door angle, Get current vehicle weapon Hash

### PR DESCRIPTION
**Pull request by qiangqiang101**
Add Blip Color for Franklin, Michael & Trevor in Blip, Add Set Door Angle in DoorAngle, Add Get Vehicle Current Weapon Hash in Vehicle,

### CODE REVIEW

**Comment by crosire** [comment]
Whoa. Something went wrong here. You are trying to merge our `dev_v3` branch into `master` (that won't work), rather than merging your own branch into our `dev_v3`.

**Comment by qiangqiang101** [comment]
sorry new to github here, don't really understand how it works

**Comment by qiangqiang101** [comment]
@crosire how to merging my own branch into `dev_v3`?
I got this error
Sync failed to puch local changes
It seems you do not have permission to push your changes to this repository.

**Comment by crosire** [comment]
You need to fork the repository (top right button), push the changes to this fork on your own account and then create a pull request from that one.

**Pull request closed without merging**
