### PR TITLE
Add Control class

### PR DESCRIPTION
**Pull request by leonardosnt**
I dont know what you think about the **ThisFrame** suffix, but i think that it makes it easier to understand.

### CODE REVIEW

**Comment by crosire** [comment]
I'm not sure if it is really necessary to introduce an additional static class for this. I'd prefer adding those additional methods to the "Game" class too.

**Comment by kagikn** [comment]
Even RAGE Plugin Hook doesn't have the independent control class.

**Comment by leonardosnt** [comment]
@crosire Ok, i will close.
@kagikn Ragehook is a standard? i think no.

**Comment by kagikn** [comment]
@leonardosnt I don't think RAGE Plugin Hook is a standard too. It's really eccentric.

**Comment by crosire** [comment]
@leonardosnt Sure. Also the ThisFrame suffix is a good idea, if they actually only affect the controls on the current frame (haven't tested it). Just mark the old ones as obsolete then (like you did here already).

**Comment by leonardosnt** [comment]
@crosire Ok, i will do. Thanks for attention.

**Pull request closed without merging**
