### PR TITLE
Added Shoot_Single_Bullet_Between_Coords

### PR DESCRIPTION
**Pull request by xcxooxl**
Added Shoot_Single_Bullet_Between_Coords

World.ShootBullet

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Thanks!
Would you mind rebasing/squashing your master-branch so there is only 1 commit? There is a good guide [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) explaining how to do it.

**Comment by xcxooxl** [comment]
ahh Sorry I suck at git commands.. I even got help on how to push it right =/
just wanted to contribute didn't know its so complicated =/

**Comment by JohnnyCrazy** [comment]
No problem! Took me ages to get into git :stuck_out_tongue_winking_eye: 
If you are okay with it, I can manually merge your commit?

**Comment by xcxooxl** [comment]
of course!

**Comment by IncoCode** [comment]
This is already here: #151 , sorry, @JohnnyCrazy didn't see your post :)

**Comment by JohnnyCrazy** [comment]
New PR in #151

**Pull request closed without merging**
