### PR TITLE
Some rope extensions

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
Example script:

````c#
Entity one;
Entity two;

//Somewhere in OnKeyDown under your desired key
if (one == null)
{
    one = Game.Player.GetTargetedEntity();
    UI.Notify("First entity set");
    return;
}
if (two == null)
{
    two = Game.Player.GetTargetedEntity();
    UI.Notify("Second entity set");
    return;
}

//Somewhere else in OnKeyDown :P
Rope.LoadTextures();
float distance = World.GetDistance(one.Position, two.Position);

rope = World.AddRope(Game.Player.Character.Position, new Vector3(), distance, 4, distance, 0, 10.0, true, true, true, 10.0, true);
rope.ActivatePhysics();

rope.AttachEntities(one, two, distance);
UI.Notify("Attached"); 
````

Maybe you can have a quick look at it @crosire

### CODE REVIEW

**Comment by Nacorpio** [comment]
Very good job!
I'm definitely going to make use out of this.

**Comment by crosire** [comment]
Should we call ROPE_LOAD_TEXTURES inside "World::AddRope" automatically?

**Comment by JohnnyCrazy** [comment]
Mm, it's only needed once,but it should not make a big difference

**Comment by XBLToothPik** [comment]
Should also implement _GET_ROPE_LENGTH.  Maybe as the Length property.

**Comment by JohnnyCrazy** [comment]
Done :)

**Pull request merged**
