### PR TITLE
Added many properties and methods and replaced LF with CRLF in Vehicl…

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by Frede1012** [comment]
What is the difference between your changes in Vehicle? (Not the added functions)

**Comment by IncoCode** [comment]
@Frede1012 changed the encoding.

**Comment by kagikn** [comment]
@Frede1012 added BodyHealth, HasAlarm, AlarmActive, StartAlarm.

**Comment by Frede1012** [comment]
@IncoCode Ah, okay then :-)

**Comment by kagikn** [comment]
I forgot to implement the functions to Vehicle.hpp, my bad.

**Comment by kagikn** [comment]
Can we merge this PR?

**Pull request merged**
