### PR TITLE
Added: Vehicle::LastVehicle

### PR DESCRIPTION
**Pull request by Yothri**

### CODE REVIEW

**Comment by Frede1012** [comment]
Why did you remove AlwaysKeepTask?

**Comment by Yothri** [comment]
Wasnt my intention to do, readded it.

**Comment by crosire** [comment]
Uhm, we already have this? See "Player::LastVehicle". And since this affects the player only and not the peds I think it makes more sense there.

**Comment by Yothri** [comment]
Well i didnt knew. Sorry.

#Closed

**Pull request closed without merging**
