### PR TITLE
Started to add documentation and other tweaks

### PR DESCRIPTION
**Pull request by zorg93**

### CODE REVIEW

**Comment by Fireboyd78** [comment]
I suggest leaving out the `Checkpoint.Reserved` property until we can 100% determine the proper name for it. Nice work!

**Comment by crosire** [comment]
Agreed.

**Comment by zorg93** [comment]
It has a description on native db that's pretty accurate

**Comment by crosire** [comment]
Could be renamed to "ExtraFlags" or something along those lines to make it clearer.

**Pull request merged**
