### PR TITLE
Fixed up GetAll Ped/Props/Vehicles/entites, Removed GetPedNearby peds…

### PR DESCRIPTION
**Pull request by zorg93**
…/vehicles. Changed explosion names to reflect their actual names

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Just noted, #222 covers explosion names

**Comment by zorg93** [comment]
#222 Never actually fixed the issue, they are still incorrect in the source

**Comment by JohnnyCrazy** [comment]
Yea, thats why I reopened it

**Comment by zorg93** [comment]
Oh OK

**Comment by crosire** [comment]
@JohnnyCrazy: You are aware that #222 is an issue an no pull request, so that doesn't help at all. It was correct to put this in a pull request (like this one).

**Comment by JohnnyCrazy** [comment]
Never said that this PR is wrong? I just made a reference so we close the #222 issue once we merge this PR.

**Comment by crosire** [comment]
Ah. It sounded like #222 already fixes those issues, so it does not have to be done in this PR.

**Pull request closed without merging**
