### PR TITLE
Fixed font enum

### PR DESCRIPTION
**Pull request by kagikn**
Font 0 is absolutely Chalet London 1960, not Arial. Font 6 is interesting. There is a difference between font 6 and font 4 only in Chinese, Japanese, Korean. In other languages, font 6 is same as font 4.

### CODE REVIEW

**Comment by Frede1012** [comment]
Can this be true? @nevadascout

**Comment by nevadascout** [comment]
He's right, font 0 is definitely Chalet London (`ChaletLondon`), but I'm not sure about Chalet Comprime.

Take a look at this, and see if you think fonts 6/4 are Chalet Comprime. http://www.houseind.com/fonts/chaletcomprime/viewfonts

They look a little like `Milan 1980` or `Cologne 1960`, maybe?

**Comment by kagikn** [comment]
@nevadascout Fonts 6/4 are definitely Cologne 1960. fontmap.xml and font_lib_efigs_pc.gfx
 show the proof.
font_lib_efigs_pc_gfx
fontmapxml - openiv

**Comment by nevadascout** [comment]
Alright, I believe you :P

What about those other fonts though? I can see `Arial`, `HelveticaNeueLT` and various others in your screenshots. Do we know what font ids those are?

**Comment by kagikn** [comment]
I'm not sure about those font ids. but I think that Arial isn't available in GTAV.

**Comment by nevadascout** [comment]
Alright.

So, @Frede1012, let's change Arial to `ChaletLondon` and Helvetica to `ChaletComprimeCologne` ?

Also, should we remove font 6 as it's the same as font 4?

**Comment by Frede1012** [comment]
Seems good :)

**Pull request merged**
