### PR TITLE
Added Apply Ped and Vehicle Damage

### PR DESCRIPTION
**Pull request by zorg93**
Added Show and Hide Hud components
Added get ped current weapon object
Added 3D raycasting

### CODE REVIEW

**Comment by crosire** [comment]
What does 3D raycasting do? Is it a spherical raycast? If so, we should probably rename it to something like "RaycastSphere".

**Comment by zorg93** [comment]
sort of, Instead of the ray being a line with no width its more like a cylinder that is used to detect if it hits something

**Comment by crosire** [comment]
I see. "RaycastCapsule" (that's close to [Unitys definition](http://docs.unity3d.com/ScriptReference/Physics.CapsuleCast.html))?

**Comment by zorg93** [comment]
Shall I rename to RaycastCapsule?

**Comment by crosire** [comment]
I think that would explain it better, yeah.

**Comment by zorg93** [comment]
It seems like calling a native with a nullptr argument seems to cause a crash

**Pull request merged**
