### PR TITLE
Added Control enum and some controls functions in Game

### PR DESCRIPTION
**Pull request by LibertyLocked**
I think we should have this Control enum, but I'm not sure if it is necessary to create a Controls class just to wrap CONTROLS natives.

Maybe I should have included these functions in Game class?

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
350 lines should go in their own file, looks good :+1:

**Comment by crosire** [comment]
I don't think we need a separate file here. But I would remove the rendundant "Control" in the function names: "Control::IsEnabled", "Control::IsPressed", ...

**Comment by LibertyLocked** [comment]
IS_DISABLED_CONTROL_JUST_PRESSED is used the most often, but others can be useful in some cases.

Maybe add a Game::IsControlPressed to "Game" that calls "Controls::IsDisabledControlJustPressed"?

**Comment by crosire** [comment]
Right, even better. Move all those functions into "Game" rather than "Control".

**Comment by LibertyLocked** [comment]
I think this is what you want.
In case someone needs to use control functions that are not in "Game", they can call the natives with Control enum casting to int.

**Comment by crosire** [comment]
What is the different between IS_CONTROL_JUST_PRESSED and IS_DISABLED_CONTROL_JUST_PRESSED?
The design is what I meant now, but it's a little confusing: "Game::IsKeyPressed" returns the current key state, which is functionally equal to "Game::IsControlDown", not "Game::IsControlPressed" ...
So maybe rename "Game::IsControlDown" to "Game::IsControlPressed" and "Game::IsControlPressed" to "Game::IsControlJustPressed", "Game::IsControlReleased" to "Game::IsControlJustReleased"?

**Comment by LibertyLocked** [comment]
AFAIK, the controls for IS_CONTROL_JUST_PRESSED are physical buttons (A, B, X, Y, etc), but controls for IS_DISABLED_CONTROL_JUST_PRESSED are game keybinds (Get-In-Car key, Stealth key, Shoot key, etc)

Maybe we can have both?

**Comment by zorg93** [comment]
I think its because you can disable controls using disable_control_action, Is_disabled_control_just_pressed will return true if the control is disabled and pressed, where as is_control_just_pressed would return false

**Comment by kagikn** [comment]
IS_CONTROL_PRESSED return true only if the control is enabled and pressed, so IS_CONTROL_JUST_PRESSED should return false if the control is disabled.

**Comment by LibertyLocked** [comment]
So which ones do we need here in "Game"?
Or should we stick to my original proposal, that we make a Controls class to wrap the controls natives?

**Comment by crosire** [comment]
@kagikn Just guessing from the name and how input systems in engines usually work IS_CONTROL_PRESSED returns the current state and IS_CONTROL_JUST_PRESSED returns true if the control was pressed this frame and false the follow up frames.
I still don't get the idea of "disabled controls". But we can just add both to "Game", to be on the safe side.

**Comment by kagikn** [comment]
@crosire For example, when the player is in the place that don't allow to sprint, IS_CONTROL_PRESSED will return false regardness of whether the sprint button is pressed, but IS_DISABLED_CONTROL_PRESSED will return true if the sprint button is pressed.

**Comment by crosire** [comment]
Ah. Now that makes sense. In that case we indeed should use the DISABLED overloads. So we can keep it the way it is now.

**Comment by LibertyLocked** [comment]
So we should be good now. Is there anything else we want for controls?

**Pull request merged**
