### PR TITLE
Added getter for NeonLightsColor property, added IsNeonLightsOn method

### PR DESCRIPTION
**Pull request by LibertyLocked**
Just a followup to PR #75 , I've added a getter for the NeonLightsColor property.
Also added IsNeonLightsOn method.

### CODE REVIEW

**Comment by IncoCode** [comment]
Maybe will be better add one property NeonLightsOn with getter and setter?

**Comment by LibertyLocked** [comment]
I would, but there are multiple neon light locations (as seen in my VehicleNeonLight enum).

**Comment by crosire** [comment]
But still, renaming it "NeonLightsOn" would better match the other property names.

**Comment by IncoCode** [comment]
Oh, yes, didn't notice this.

**Comment by LibertyLocked** [comment]
So if I made a "NeonLightsOn" property, should the getter return true if any of the 4 neon lights are on? Because there is an on/off state for each of them

**Comment by crosire** [comment]
Forgive my stupidity (a second time now). Just ignore that :smile:

**Pull request merged**
