### PR TITLE
Added missing boolean parameter to GET_GROUND_Z_FOR_3D_COORD within GetGroundHeight

### PR DESCRIPTION
**Pull request by Jitnaught**

### CODE REVIEW

**Comment by kagikn** [comment]
Every function treats missiong parameters as 0, so this change doesn't affect `GET_GROUND_Z_FOR_3D_COORD` at all.

**Comment by Jitnaught** [comment]
Didn't know that, thanks.

**Comment by crosire** [comment]
That doesn't make this pull request wrong though.

**Comment by kagikn** [comment]
I see, this PR can prevent people from getting confused.

**Pull request merged**
