### PR TITLE
Added Reload Scripts When Insert Is Pressed Functionality

### PR DESCRIPTION
**Pull request by nuvious**
Added functionality to reload scripts when the 'insert' button is pressed. This was advertised on the getting started page but not implemented as far as I could see in the code or testing and very much needed for my development.

Built and tested with one of my mods where failure to fully reload the script would be apparent and obvious. Seems to work.

### CODE REVIEW

**Comment by crosire** [comment]
This key binding was explicitly removed from v3 since scripts an be reloaded via the console. See commit 69c18f8ba38490ddafb38c24d6c27f18cede9ac0.

**Comment by nuvious** [comment]
Oh cool. Is there documentation for console commands and/or can we update the wiki?

**Comment by crosire** [comment]
The wiki isn't updated for v3, since it's still subject to change. But right now the console commands available by default are the following:
`Help()`
`Load(filename)`
`Reload(filename)`
`List()`
`Abort(filename)`
`Clear()`

**Comment by JohnnyCrazy** [comment]
But I guess a reload overload for all scripts would be nice to have

**Comment by crosire** [comment]
`Reload()`?

**Comment by Tanjitsu** [comment]
I would ask the opposite... Rather than rebooting the whole dll, can we reload a single script inside our script domain ?

Console.Reload("Namespace:Class")

**Comment by zorg93** [comment]
Average user isnt going to know the namespace and class a mod is in

**Comment by zorg93** [comment]
Usually, but if he needs to, reloading the whole dll would make more sense to them

**Comment by kagikn** [comment]
Now v2 has no way to reload scripts in v2 unless the game is reloaded... Would you revert the reload key in v2? @crosire

**Comment by crosire** [comment]
Uh, v2 still has the reload key?!

**Comment by kagikn** [comment]
No, it's deleted for some reason in a9aa85a.

**Comment by crosire** [comment]
Oh. That was unintended then.

**Pull request closed without merging**
