### PR TITLE
Added Task.Cower

### PR DESCRIPTION
**Pull request by ricci07**
Simple to begin with, needed to get a grip.

### CODE REVIEW

**Comment by crosire** [comment]
Doesn't GET_SCREEN_RESOLUTION always return 1280x720 no matter what? So do we really need it?

**Comment by screeny05** [comment]
Question aside: has anybody ever tested `GET_SCREEN_RESOLUTION` on a screen
with size lower than 1280x720? Does the return value depend on the
resolution set ingame?
Am 07.05.2015 09:22 schrieb "crosire" <notifications@github.com>:

**Comment by CrossCRS** [comment]
Just tested it on 1920x1080 and 800x600, returned 1280x720 in both cases.

**Comment by ricci07** [comment]
Yeah, I hadn't tested, I was up all night trying to figure out git. I remove that then.

**Comment by crosire** [comment]
You can just do that in a following commit, Github will append it to this.pull request automatically =)

**Comment by ricci07** [comment]
Alright I'll get to it when home :)

**Comment by JohnnyCrazy** [comment]
Yea it's kinda strange, he also used some unnamed Native-Call for calculating the line height/width. Still don't know what it does :joy:

**Comment by ricci07** [comment]
Exactly, how does he know what they do?

On skype he said 'see how they do it in the scripts' for various questions I asked. So I'm guessing he also has no idea what it does and just grabs the entire code block and changes the parameters and just trusts it does something.  

I was asking about why ADD_EXPLOSION stops rendering the camera shake and explosion particle effects after using it it a few times. I never got it to work again, even after restart/reload.

Have you guys have this problem, with ADD_EXPLOSION?

**Comment by crosire** [comment]
He takes his information from the [decompiled GTA V scripts](https://dl.dropboxusercontent.com/u/1237747/games.gta/gtav.xsc.decompiled.7z). Just do a search for whatever native you are interested in check how the game uses it to figure out which parameter does what.

**Comment by ricci07** [comment]
Yes, I was talking about the hashed ones like...

UI::0x67S7H89(4, rptr(a_01)), 1, 0, 0,0, 1)

That is an example, not a real function.

**Comment by crosire** [comment]
Trial and error I guess.

**Comment by ricci07** [comment]
Ok, I'm home, got to find out about this git branch thing and remove screen_get_resolution (or replace with custom method, like screen_get_dimentions)

**Comment by crosire** [comment]
I'd start by removing the screen resolution property and pushing that to master, so I can merge things into the codebase with this pull request. The branch stuff is interesting for any new patch you may come up in the future.

**Comment by ricci07** [comment]
Ok, done, can I put anything in a branch? Be it new lines in game.cpp/game.hpp or ped.cpp/ped.hpp or is it topic-specific?

**Comment by crosire** [comment]
I suggest reading this: https://help.github.com/articles/github-flow-in-the-browser/

**Pull request merged**
