### PR TITLE
Added some more references for script compiling

### LINKED ISSUE #344: loading .cs files missing dll References?
if I create a .cs script and reference System.Xml for example I get this when trying to load the game:

Failed to compile 'FiveStarResponse.cs' with 1 error(s):
   at line 12: The type or namespace name 'Xml' does not exist in the namespace 'System' (are you missing an assembly reference?)

If I compile the .cs it works without problem. Any way to fix this? Same issue with System.Linq

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
This PR will close #344 

@crosire

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
My bad, some of those DLL don't exist, will fix it tomorrow and update it.

**Comment by Fireboyd78** [comment]
Looks like the only one we need to add is `System.Core.dll`.

**Comment by crosire** [comment]
Fine with me.

**Comment by JohnnyCrazy** [comment]
If I understand it correctly, we need to reference more than `System.Core.dll`.

I just checked it with `ILSpy`, and it seems like only some `IO` classes are inside `System.Core.dll`, most of them are in `mscorlib.dll`

**Comment by Fireboyd78** [comment]
I used the Object Viewer in Visual Studio and everything seems to be in `System.Core` -- just add that and the XML ones for now and if any other issues come up, then we'll go from there.

**Comment by Fireboyd78** [comment]
And I'm pretty sure we don't need to reference `mscorlib`, how else would the scripts even be working without it? It's literally the backbone of the .NET framework, lol.

**Comment by crosire** [comment]
```mscorlib.dll``` is referenced by default, yes.

**Comment by JohnnyCrazy** [comment]
Done, should be good to go @crosire

**Pull request merged**
