### PR TITLE
Audio Class

### PR DESCRIPTION
**Pull request by TrentGoodall**
A new class for all audio related functions.

*Audio class*

- Added function **GetSoundID**
- Added function **HasSoundFinished**
- Added function **PlaySoundFromCoord**
- Added function **PlaySoundFromEntity**
- Added function **PlaySoundFrontEnd**
- Added function **ReleaseSoundId**
- Added function **SetAudioFlag**
- Added function **StopSound**

*More to come...*

### CODE REVIEW

**Comment by crosire** [comment]
Looks good. I would rename "PlaySoundFrontEnd" to "PlaySoundFrontend" though, because that seems to be the more common way of spelling it.

**Comment by leonardosnt** [comment]
merge plz

**Comment by timnboys** [comment]
Please do merge this as this is one thing besides the checkpoint class & animationset class I need to port over a script from gta iv scripthookdotnet to gtav scripthookvdotnet

**Comment by Nacorpio** [comment]
When is this going to be merged?

**Pull request merged**
