### PR TITLE
Added Vehicle NeonLightsColor property and SetNeonLightsOn method.

### PR DESCRIPTION
**Pull request by LibertyLocked**
Not exactly sure if Neon Lights count as a Mod thought, so I'm not sure if having a SetNeonLightsOn() method is a good idea.
But the NeonLightsColor property should definitely be there.

### CODE REVIEW

**Comment by Nacorpio** [comment]
I don't think the neon lights are a mod.
So good job.

**Comment by crosire** [comment]
I'd make the method a (setter only) "NeonLightsOn" property, since all other vehicle-light-related things are too.

**Comment by LibertyLocked** [comment]
I agree, but to set neon lights I have to specify which light (as seen in my VehicleNeonLight enum) to turn on/off. Unless you are saying turning all the neon lights on?

**Comment by crosire** [comment]
Oh, right, didn't see that. Alright, more useful as a method then, true.

**Pull request merged**
