### PR TITLE
Added Add(Owned)Explosion to World.

### PR DESCRIPTION
**Pull request by Yothri**
Added AddExplosion && AddOwnedExplosion to World.

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Is there a List of explosion types somewhere? If so, we could supply an enum

**Comment by Yothri** [comment]
Not yet, but when i get home i will try them all out and create one.
ExplosionType Enum will be submitted soon.

**Comment by crosire** [comment]
They probably equal the ones from GTAIV (as the rest of the native didn't really change), could somebody confirm that?
```c#
public enum class ExplosionType
{
		Default,
		Molotov,
		Rocket,
};
```

**Comment by Yothri** [comment]
I already tried at home explosionTypes from 1-32 (i guess it was 32) so you might be correct, because most of them were the same (fire explosions) but yeah. I will try to find those in IDA and then my next commit to AddExplosion will contain the enum.

**Comment by crosire** [comment]
Why did you close?

**Comment by Yothri** [comment]
Last commit contained error... Thought, closing the pull request would forbid you to merge into your project. Wanted to fix it first.

**Comment by crosire** [comment]
Ah, alright, no worries, just got me confused =).

**Pull request closed without merging**
