### PR TITLE
Added mpexecutive vehicle hashes

### PR DESCRIPTION
**Pull request by UnknownModder**
Vehicle hashes for mpexecutive update (1.0.757.2).

### CODE REVIEW

**Comment by crosire** [comment]
These were already added in #499 ...

**Comment by UnknownModder** [comment]
@crosire Oh, I'm sorry. Didn't see that even though I checked all PRs.

**Comment by crosire** [comment]
No worries. It's a bit confusing right now, since we have two development branches (dev_v2 and dev_v3).

**Comment by zorg93** [comment]
You wasted the 500th pull request on this :-1: :-1: :-1: :-1:

**Comment by UnknownModder** [comment]
@zorg93 I'll let you waste the 555th ;)

**Comment by zorg93** [comment]
You've given me 2 reasons to hate you now. p.s heres the seconds http://gtaforums.com/user/707372-unknown-modder/ :)

**Comment by UnknownModder** [comment]
@zorg93 Why not change your name to zorg93 ??
Btw, I'm going to change my name in 6-12 months so you only have one reason left to hate me :) :+1:

**Pull request closed without merging**
