### PR TITLE
Add WeaponAsset

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by Fireboyd78** [comment]
You should implement the `IEquatable<T>` interface since you've already got an `Equals` method in there.

**Comment by kagikn** [comment]
I totally agree. This is a value type, so I’ll implement `IEquatable<T>` to this.

**Comment by kagikn** [comment]
I confirmed `REQUEST_WEAPON_ASSET` has effect. For example, in a new game, we can't shoot rpg with `SHOOT_SINGLE_BULLET_BETWEEN_COORDS` unless we call `REQUEST_WEAPON_ASSET`.

**Comment by kagikn** [comment]
I said `WeaponAsset` is useful in some cases...

**Comment by crosire** [comment]
Absolutly nothing. Doesn't mean it gets merged right away, I prefer to hold some features back for future versions.

**Comment by JohnnyCrazy** [comment]
to avoid further misunderstandings, we could assign [milestones ](https://github.com/crosire/scripthookvdotnet/milestones) to the PR/Issue? @crosire 

Going that way helps people know when their PR will be released/merged.

**Comment by crosire** [comment]
Great idea :+1:

**Pull request merged**
