### PR TITLE
Massive overhaul of UI

### PR DESCRIPTION
**Pull request by zorg93**
Turns out i was wrong, multiplying the width results in the image being scaled up. Fixed by changing it to dividing the height by the aspect ratio and results work pretty well
`			new UIRectangle(new Point(200-Size/2, 200-Size/2), new Size(Size, Size), Color.Black).Draw();
			UI.DrawTexture(SpeedoBG, 0, -9995, 100, new Point(200, 200), new PointF(0.5f, 0.5f), new Size(Size, Size), rot, Color.White);`

ignore the other texture in the bottom right, but thats showing its working at least

### CODE REVIEW

**Comment by zorg93** [comment]
@JohnnyCrazy @crosire can you add a 3.0 Tag to this as it will break some scripts due to removing the aspect ratio parameter from UI.DrawTexture

**Comment by Guad** [comment]
If you're going to break compatibility, I'd suggest using PointF & SizeF. Using integers isn't accurate enough in some cases.

**Comment by zorg93** [comment]
The only benefit with using a floating point system would be that you have access to more pixels on displays > 1280*720. However that would only really be noticeable on 2.5K+ displays. As all draw calls by SHV.Net are done this way, everything lines up properly using the current Integer system.

**Comment by Guad** [comment]
But what if I want to align with game UI? The majority of players have displays with bigger res than 1280x720. Are there any downsides apart from maybe inconsistencies with other SHV.Net UI eñements?

**Comment by zorg93** [comment]
@Guad The downsides are inconsistencies and simplicity. If we were to change this to PointF and SizeF then everything else should also change. which means all scripts using UI elements would need changing to use PointF and SizeF aswell

**Comment by Guad** [comment]
The problem is that if I need better precision for other UI elements, I can use the natives and implement them myself, but I have no other access to ScriptHookV's drawTexture method. Maybe an overload?

**Comment by zorg93** [comment]
@crosire Whats your opinion on using Floating points instead of Integers?

**Comment by crosire** [comment]
Additional overloads which take floating point parameters would be the simplest solution (as Guad mentioned). That preserves the integer ones for simplicity, but also gives the option for more precision.

**Comment by zorg93** [comment]
If I'm going to rework this, would it perhaps be better making Textures a UIElement subclass, kind of like UISprite now

**Comment by zorg93** [comment]
As this is going in 3.0 can we not just make all UI elements based off floats, keep everything the same

**Comment by JohnnyCrazy** [comment]
I don't know if we should ditch the coordinate-based system completely. Its still good for supporting different resolutions.

**Comment by zorg93** [comment]
Im saying keep the coordinate based system, but use PointF and SizeF instead of Point and Size to represent it. It would still have a limited range of (0.0f, 1280.0f),(0.0f, 720.0f), but it would give the added precision especially for people playing with large resolution monitors

**Comment by JohnnyCrazy** [comment]
Sounds Good

**Comment by crosire** [comment]
Jup. By the way. While we are having fun breaking compatibility for everything, how about putting all the UI stuff in a GTA.UI namespace (while removing the UI prefix from class names)?

**Comment by zorg93** [comment]
Will sort that out now :)
What to do about things like UI.Notify. sense says put it in the GTA.UI namespace, but then you'd have GTA.UI.UI.Notify

**Comment by crosire** [comment]
If only .NET had global functions...
We could put those in ```Game```, or in a ```UI.Screen``` class or something along those lines.

**Comment by zorg93** [comment]
I almost have everything working, Just testing. Scripts will need a fair bit of reworking with this though. @Guad I have made changes to NativeUI to accommodate these changes so if you want I can put in a PR on NativeUI

**Comment by JohnnyCrazy** [comment]
Guess we should either create a wiki article for upgrading to 3.x or a note somewhere

**Comment by zorg93** [comment]
A fair bit of work as in changing a few references. IntelliSense will tell you whats wrong though

**Comment by zorg93** [comment]
@crosire the simplest would be to rather than having a GTA.UI namespace, having subclasses inside the UI class. However I feel a little bit against doing that, seems like bad coding organisation/practice

**Comment by crosire** [comment]
```c#
namespace GTA.UI
{
    static class Screen; // Width, Height, Notify, ShowSubtitle, *Hud*, WorldToScreen
    class Element;
    class Text;
    class Sprite;
    class Texture; // Create an index for each instance automatically
    class Rectangle;
    class Container;
}
```

**Comment by zorg93** [comment]
Screen isn't the best name as that causes ambiguity between System.Windows.Forms.Screen

**Comment by Guad** [comment]
@zorg93 That'd be great, thanks.

**Comment by zorg93** [comment]
I'll hold back on the PR until 3.0 is out though, but it seems to be working ok - http://puu.sh/p4MSL/3f53365ab2.jpg. the only thing i havent tested is CustomTextures. kind of ironic really :p anyway if you want to have a look at the changes so far -> https://github.com/zorg93/NativeUI

**Comment by Guad** [comment]
Looks great, thanks a lot. I'll create & merge it into another branch, along with some customization features.

**Comment by zorg93** [comment]
Hopefully as Size and Point will implicitly be casted to SizeF and PointF people should have no issues changing their current scripts from old NativeUI to the new one

**Comment by Fireboyd78** [comment]
Change `UI.Screen` to `UI.Window` and you're good to go!

**Comment by crosire** [comment]
Merged into ```dev_v3``` in c34d3d8de916da547f752235f3a202608253718e.

**Comment by crosire** [comment]
We decided to keep it named ```Screen``` for now, because we couldn't come up with a better name. ```Window``` sounds too much like you can create dialog windows with the class and ```Display``` and the sorts didn't convince either. Instead one can add ```using Screen = GTA.UI.Screen;``` to the file top in C# to overwrite the ambiguous name. Or alternatively ```using UI = GTA.UI;``` and always reference it via ```UI.Screen```.

**Pull request closed without merging**
