### PR TITLE
Update vehicle memory offsets for v1.0.1180.2

### PR DESCRIPTION
**Pull request by kagikn**

### CODE REVIEW

**Comment by crosire** [comment]
The dreaded space/tabs issue is back for another round 😃.

**Comment by kagikn** [comment]
Okay, solved :stuck_out_tongue:.

**Comment by kagikn** [comment]
Merged this PR bacause this is just a hotfix. When I add, or delete some methods or properties, I'll wait for crosire's decision.

**Comment by crosire** [comment]
:+1:

**Pull request merged**
