### PR TITLE
Added Console + IsOnMiniMap method to Blips

### PR DESCRIPTION
**Pull request by Frede1012**
I implemented a console for the scripthook, it may currently be hooked up wrong relative to @crosire's logging and scripting structure. Which causes some issues (with input), but i would say that it is a good first step into having a scripting console. It could be changed in the future to be better implemented and better fit with the structure. This is where i would like the help of you guys (hence the pull request). Also, i wasn't sure how to structure a console command/input system, but the current console has methods that support input :)

Overall, the console is pretty much ready to use (for logging purposes), but i would like some help with implementing it better.

### CODE REVIEW

**Comment by crosire** [comment]
Good start! Some things I noticed while trying:
- Your "Console::HandleInput" is currently accepting both keydown and keyup events, which means every keypress is evaluated twice (press "A" once and you get two "A"s in the console, one when you pressed the key and the second one when you let it go again).
- "Keys::Oemtilde" seems to be occupied by the game for cheat input by default already.
- Any reason you have both a constructor and an "Initialize" method? The latter seems redundant.

**Comment by Frede1012** [comment]
@crosire 
Thanks!
- This is one of the problems with my current implementation, how would i only use one event?
- Oemtilde seems to be correspond to a different key on different computers, my tilde doesn't seem to activate the cheat input.
- I followed the structure of the other menu classes, which are strucured that way. I am not sure why, maybe that should be changed too? @StijnBrouwer

**Comment by crosire** [comment]
The "status" parameter of "ScriptDomain::DoKeyboardMessage" is true when a key down event is recieved and false if it's a key up event.

**Comment by Frede1012** [comment]
@crosire The console seems to be stable enough to be merged into the master branch. The only thing missing is handling the input to execute commands.

**Comment by Frede1012** [comment]
@crosire So aren't you going to merge my request or?

**Comment by crosire** [comment]
Put into new feature branch at https://github.com/crosire/scripthookvdotnet/tree/feature/console

**Pull request closed without merging**
