### PR TITLE
Added Shoot_Single_Bullet_Between_Coords

### PR DESCRIPTION
**Pull request by xcxooxl**
Added Shoot_Single_Bullet_Between_Coords

### CODE REVIEW

**Comment by mlgthatsme** [comment]
Typo at line 21

**Comment by IncoCode** [comment]
Nataive :+1:

**Comment by xcxooxl** [comment]
maybe when I alt-tabbed to copy the codes I miss clicked or somthing.. 

still the code is working for shooting bullets

**Comment by Frede1012** [comment]
@xcxooxl You need to fix the typo, otherwise the project wont compile.. Also, why did you submit 3 pull requests for the same thing?

**Comment by xcxooxl** [comment]
I dont know how to add 2 files at once?

I need to update both world.cpp and world.hpp

**Comment by Frede1012** [comment]
When you push to your current branch (which is also the branch your pull request comes form) your pull request will be updated.
Consider using Visual Studio's built-in Git support, since its a lot easier.

**Comment by IncoCode** [comment]
Or SourceTree, tortoisegit.

**Pull request closed without merging**
