### PR TITLE
Patch

### PR DESCRIPTION
**Pull request by Tanjitsu**
Commit various changes.

### CODE REVIEW

**Comment by Nacorpio** [comment]
"Changed ped.OpenParachute to ped.ParachuteOpen."

Why?

**Comment by Tanjitsu** [comment]
it seems to make more sense to follow the format type/action.
ped.Task.ParachuteTo
ped.ParachuteOpen;
ped.ParachuteTo
ParachuteLandingType
ParachuteState

ect.

**Comment by kagikn** [comment]
the Parachute in ParachuteTo is **verb**, but the verb in OpenParachute is **Open, not Parachute**. ParachuteOpen doesn't make sense at all.

**Comment by crosire** [comment]
Agreed. `OpenParachute` is a lot cleaner.

**Comment by Tanjitsu** [comment]
I am terrible at naming stuff.

ped.ParachuteTo should be something more like ped.SetParachuteTarget

SET_PARACHUTE_TASK_TARGET can be used before or during the ped.Task.ParachuteTo to update the destination position.

**Comment by Tanjitsu** [comment]
Closing this for re-submission in parts.

**Pull request closed without merging**
