### PR TITLE
Added Vector3::Around, Vector3::RandomXY.

### PR DESCRIPTION
**Pull request by IncoCode**
Some useful methods that was in 4 .net script hook.
Also added Helper class (now contains only initialized random). In the future, it can contains methonds like StrToKey and etc.

### CODE REVIEW

**Comment by IncoCode** [comment]
How about this pull request?

**Comment by crosire** [comment]
I'm not sure we really need this in the core Script Hook, or if it's better to leave such helper functions to the script developers?

**Comment by IncoCode** [comment]
Well, 4 .net scripthook has Vector3::Around. But i don't know how it was implemented. But i think, in 4 .net scripthook also used Random for this method.

**Comment by crosire** [comment]
I know, it's just that I really like the KISS principle, which is why those functions were initially removed in the first place (and to get around possible licensing issues). The Vector class is a straight copy from IV .NET Scripthook other than that.

**Comment by IncoCode** [comment]
4 .net scripthook is open source? :open_mouth:
Well, if this code same or similar on 4 .net scripthook Vector class and there may be some licensing issues - then you should close this pull request :worried:

**Comment by crosire** [comment]
Yeah, it's open source (can be downloaded from HazardX's site).
This is just my personal opinion, so I'm open for discussion whether we should implement these methods. Would be really nice to hear yet another point of view =).

**Comment by IncoCode** [comment]
If this hook only for run .net scripts in gta 5 - maybe, we shouldn't.
If one of the objectives of this hook is to facilitate the development of gta 5 scripts - helper methods (which can often be used in users scripts) should be here.

**Comment by crosire** [comment]
Alright. Mind if you resubmit a pull request with those Vector3 additions then (since this one got closed automatically)? I'd prefer to not have that separate Helper class + file though.

**Pull request merged**
