### PR TITLE
Fix natural motion on newer game versions (>v1.0.877.1)

### PR DESCRIPTION
**Pull request by CamxxCore**

### CODE REVIEW

**Comment by CamxxCore** [comment]
Okay well the build is failing because the Scripthook SDK doesn't include newer updates in the eGameVersion enum. Wasn't really sure on the best way to handle this. Maybe just cast to eGameVersion?

**Comment by kagikn** [comment]
And sadly, we can't the GameVersion enum (in SHVDN) in cpp/hpp files, for now. If we port core code to C#, we can also use it in core files, though.

**Comment by crosire** [comment]
You could just add a `#define VER_1_0_877_1_STEAM ...` to the top of `NativeMemory.cpp` for now.

**Comment by CamxxCore** [comment]
Just added it (:

**Pull request merged**
